#!/bin/bash

# esv1demo: build VSAM ESDS cluster VCDT ESV1.390 and run ESV1SP, ESV1SG, diff

########################################
# print error message and exit
########################################

function errmsg {
    echo ERROR: $1\; exiting
    exit 8
}

########################################
# setup
########################################

cd $(dirname $0)     # set to directory of script - z390/vsam1/demo/bash
cd ../../..          # up to z390

pgmname=esv1demo
vsampath=vsam1/demo
zvsam="zvsam(1)"
trace=""
if [ "$1" = "traceall" ]; then trace=traceall; shift; fi

########################################
# code
########################################

rc=0

# run ESV1SP seq put to build ESV1.VES

export QFILE=${vsampath}/ESV1.TF1
export VFILE=${vsampath}/DEMOCAT.ESV1
rm -f ${vsampath}/ESV1.VES
rm -f ${vsampath}/ESV1.VX0
bash/asmlg ${vsampath}/ESV1SP $1 $2 $3 $4 $5 $zvsam $trace
rc=$?
if [ $rc -ne 0 ]; then errmsg "error in ESV1SP"; fi

# run ESV1SG seq get from ESV1.VES to ESV1.TF2

rm -f ${vsampath}/ESV1.TF2
export QFILE=${vsampath}/ESV1.TF2
export VFILE=${vsampath}/DEMOCAT.ESV1
bash/asmlg ${vsampath}/ESV1SG $1 $2 $3 $4 $5 $zvsam $trace
rc=$?
if [ $rc -ne 0 ]; then errmsg "error in ESV1SG"; fi

# compare input and output QSAM files

diff ${vsampath}/ESV1.TF1 ${vsampath}/ESV1.TF2 > ${vsampath}/${pgmname}.DIF
rc=$?
if [ $rc -ne 0 ]; then errmsg "ESV1.TF1 not equal to ESV1.TF2"; fi

exit $rc
