.* MVS 3.8J PUBLIC DOMAIN
         MACRO
&NAME    ACI   &C,&I                    ADD TO COUNTER
         LCLA  &CT,&V
&V       SETA  &I
         AIF   (&V LE 65535).AC0
         MNOTE 8,'***  IHB421 IMMEDIATE VALUE EXCEEDS ALLOWED MAXIMUM'
.AC0     ANOP
&CT      SETA  16*&C
         AIF   ('&C' LE '15').AC1
         MNOTE 8,'***  IHB416  COUNTER VALUE MUST BE 0-15'
&CT      SETA  0
.AC1     ANOP
&NAME    DC    0H'0',X'AA',AL1(&CT),AL2(&I)
         MEND

