.* MVS 3.8J PUBLIC DOMAIN
         MACRO
&NAME    CHI   &H,&I                    COMPARE HDR TO IMMEDIATE
         LCLA  &V
&V       SETA  &I
         AIF   (&V LE 255).CH0
         MNOTE 8,'***  IHB421 IMMEDIATE VALUE EXCEEDS ALLOWED MAXIMUM'
.CH0     ANOP
         AIF   ('&H' LT '12').CH1
         MNOTE 8,'***  IHB354  HEADER BYTE NOT 0-11; 0 ASSUMED'
&NAME    DC    0H'0',X'80',AL1(&I)
         AGO   .END
.CH1     ANOP
&NAME    DC    0H'0',AL.4(8),AL.4(&H),AL1(&I)
.END     MEND

