#!/bin/bash
# runtests: assemble, link, and run zVSAM V2 tests
# Optional: tron|troff, then path to z390Archive clone (forwarded to tstload)

########################################
# print error message and exit
########################################

function errmsg {
    echo "ERROR: $1; exiting"
    exit 8
}

########################################
# setup
########################################

cd "$(dirname "$0")"
cd ../..

vsampath=vsam2
zvsam="zVSAM(2)"

########################################
# code
########################################

rc=0

# GENCB test
${vsampath}/bash/testgncb
rc=$?
if [ $rc -ne 0 ]; then errmsg "testgncb assembly/link/execute error"; fi

# MODCB test
${vsampath}/bash/testmdcb
rc=$?
if [ $rc -ne 0 ]; then errmsg "testmdcb assembly/link/execute error"; fi

# SHOWCB test
${vsampath}/bash/testshcb
rc=$?
if [ $rc -ne 0 ]; then errmsg "testshcb assembly/link/execute error"; fi

# TESTCB test
${vsampath}/bash/testtscb
rc=$?
if [ $rc -ne 0 ]; then errmsg "testtscb assembly/link/execute error"; fi

# TSTLOAD suite
${vsampath}/bash/tstload
rc=$?
if [ $rc -ne 0 ]; then errmsg "tstload suite failed"; fi

exit $rc
