#!/bin/bash

# testshcb: assemble, link module using SHOWCB macro

########################################
# setup
########################################

cd $(dirname $0)     # set to directory of script - z390/vsam2/bash
cd ../..             # up to z390

vsampath=vsam2
zvsam="zvsam(2)"

########################################
# code
########################################

rc=0

# run build TESTSHCB.390

bash/asml ${vsampath}/mlc/TESTSHCB $1 $2 $3 $4 $5 $zvsam
rc=$?
if [ $rc -ne 0 ]; then echo "error in testshcb"; fi

exit $rc
