#!/bin/bash
#######################################################################
# z390 - Mainframe assembler emulator and run-time engine
# Copyright (C) 2021 z390 Assembler LLC
#
# This file is part of z390.
# z390 is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# z390 is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, see <https://www.gnu.org/licenses/>.
#######################################################################

# testmpcb: assemble, link and run module checking ACB/RPL against their mappings

########################################
# setup
########################################

cd $(dirname $0)     # set to directory of script - z390/vsam2/bash
cd ../..             # up to z390

vsampath=vsam2
zvsam="zvsam(2)"

########################################
# code
########################################

rc=0

# build and run TESTMPCB.390; the checks are at run time, so asmlg not asml

bash/asmlg ${vsampath}/mlc/TESTMPCB $1 $2 $3 $4 $5 $zvsam
rc=$?
if [ $rc -ne 0 ]; then echo "error in testmpcb"; fi

exit $rc
