site_name: z390
site_author: z390 Development team
copyright: "&copy; 2021 Don Higgins. All rights reserved"

repo_url: https://github.com/z390development/z390/
edit_uri: edit/main/doc/
remote_branch: gh-pages-beta

plugins:
  - search
  - awesome-pages
  - with-pdf:
      cover_subtitle: Mainframe assembler and emulator toolkit
      enabled_if_env: ENABLE_PDF_EXPORT
      output_path: pdf/z390.pdf

theme: 
  name: material
  custom_dir: doc_overrides
  features:
    - navigation.tabs
    - navigation.tabs.sticky

docs_dir: doc

markdown_extensions:
  - admonition
  - footnotes
  - meta
  - attr_list
  - def_list
  - pymdownx.highlight
  - pymdownx.tabbed
  - pymdownx.superfences
  - pymdownx.critic
  - pymdownx.smartsymbols
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

nav:
  - Home: index.md
  - Getting started: getting_started.md
  - User guide: user_guide.md
  - ... | reference/**
  - ... | contributing/**
