CD..
SET TESTFILE=rpi\TESTFILE.TXT
CALL bat\MZ390 rpi\SAMPLE3 SYSMAC(MAC+.) SYSCPY(MAC+.)
IF ERRORLEVEL 1 GOTO WRONG
CALL bat\LZ390 rpi\SAMPLE3
IF ERRORLEVEL 1 GOTO WRONG
CALL bat\EZ390 rpi\SAMPLE3
IF ERRORLEVEL 1 GOTO WRONG
GOTO END
:WRONG
oayse revuew error
REM ERROR ERROR ERROR
:END
pause review end