        MACRO
.**********************************************************************
.* z390 - Mainframe assembler emulator and run-time engine
.* Copyright (C) 2021 z390 Assembler LLC
.*
.* This file is part of z390.
.*
.* z390 is free software; you can redistribute it and/or modify
.* it under the terms of the GNU General Public License as published by
.* the Free Software Foundation; either version 2 of the License, or
.* (at your option) any later version.
.* z390 is distributed in the hope that it will be useful,
.* but WITHOUT ANY WARRANTY; without even the implied warranty of
.* MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
.* GNU General Public License for more details.
.*
.* You should have received a copy of the GNU General Public License 
.* along with this program; if not, see https://www.gnu.org/licenses.
.**********************************************************************
.* 04/04/16 INITIAL CODING BY MELVYN MALTZ
.**********************************************************************
         ZVSAMMAP
*
* zVSAM SPACEMAP BLOCK
*
ZVSAMMAP DSECT
MAPXLRA  DS    XL8                XLRA of 1st block addressed
*                                 by this block
MAPBITS  DS    0B                 Bitstring
*                                 00=unallocated
*                                 01=enough space for a small variable
*                                 10=has available space
*                                 11=full
         MEND
