#!/bin/bash

# runasmtests: regression test z390 instructions
# 2022-05-07 DSH add TESTDC1-3, TESTASC1 tests for #233 blanks in DC nominal values
set -e              # exit on all errors
cd $(dirname $0)    # set to directory of script - rt/bash
cd ..               # up to rt
cd ..               # up to z390

sysmac='sysmac(mac)'
optable='optable(z390)'

bash/asm   tests/TESTINS1 trace noloadhigh $sysmac
bash/asmlg tests/TESTINS2 trace noloadhigh $sysmac
bash/asmlg tests/TESTINS3 trace noloadhigh $sysmac
bash/asmlg tests/TESTINS4 trace noloadhigh $sysmac
bash/asmlg tests/TESTINS5 trace noloadhigh $sysmac $optable
bash/asmlg tests/TESTDFP1 trace noloadhigh $sysmac $optable
bash/asmlg tests/TESTDFP2 trace noloadhigh $sysmac $optable
bash/asmlg tests/TESTLITS trace noloadhigh $sysmac
bash/asmlg rt/mlc/TESTAMPS trace noloadhigh $sysmac $optable
bash/asmlg rt/mlc/IS215 trace noloadhigh $sysmac $optable
bash/asmlg rt/mlc/TESTDC1  trace noloadhigh $sysmac $optable
bash/asmlg rt/mlc/TESTASC1 ASCII trace noloadhigh $sysmac $optable
bash/asmlg rt/mlc/TESTDC2  trace noloadhigh $sysmac $optable
bash/asmlg rt/mlc/TESTDC3  trace noloadhigh $sysmac $optable
rt/bash/zopcheck

# if we get here, there were no errors
echo "Verify tests ran without errors"
exit 0
