#!/bin/bash
# runcbltests: run z390 zcobol sample regression tests

set -e              # exit on all errors
cd $(dirname $0)    # set to directory of script - rt/bash
cd ..               # up to rt
cd ..               # up to z390

bash/cblclg zcobol/tests/TESTADD1 $1 $2 $3 $4 $5 $6 $7 $8 $9
bash/cblclg zcobol/tests/TESTADD2 $1 $2 $3 $4 $5 $6 $7 $8 $9
bash/cblclg zcobol/tests/TESTIF1 $1 $2 $3 $4 $5 $6 $7 $8 $9
bash/cblclg zcobol/tests/TESTIF2 $1 $2 $3 $4 $5 $6 $7 $8 $9
bash/cblclg zcobol/tests/TESTIF3 $1 $2 $3 $4 $5 $6 $7 $8 $9
bash/cblclg zcobol/tests/TESTMOV1 $1 $2 $3 $4 $5 $6 $7 $8 $9
bash/cblclg zcobol/tests/TESTMOV2 $1 $2 $3 $4 $5 $6 $7 $8 $9
bash/cblclg zcobol/tests/TESTMOV3 $1 $2 $3 $4 $5 $6 $7 $8 $9
bash/cblclg zcobol/test/YOUZPI1 $1 $2 $3 $4 $5 $6 $7 $8 $9

# if we get here, there were no errors
echo "Verify ZCOBOL regression tests ran without errors"
exit 0
