#!/bin/bash
# runcbltests: run z390 zcobol sample regression tests

set -e              # exit on all errors
cd $(dirname $0)    # set to directory of script - rt/bash
cd ..               # up to rt
cd ..               # up to z390

bash/cblclg zcobol/tests/TESTADD1 $1 $2 $3 $4 $5 $6 $7 $8 $9
bash/cblclg zcobol/tests/TESTADD2 $1 $2 $3 $4 $5 $6 $7 $8 $9
# TESTCAL3 statically calls TESTASM4 - link them together
bash/asm    zcobol/tests/TESTASM4 $1 $2 $3 $4 $5 $6 $7 $8 $9
bash/cblcl  zcobol/tests/TESTCAL3 $1 $2 $3 $4 $5 $6 $7 $8 $9
# TESTCAL1 statically calls TESTCAL2 and dynamically calls TESTCAL3
bash/cblc   zcobol/tests/TESTCAL2 $1 $2 $3 $4 $5 $6 $7 $8 $9
bash/cblclg zcobol/tests/TESTCAL1 $1 $2 $3 $4 $5 $6 $7 $8 $9
bash/cblclg zcobol/tests/TESTCMP1 $1 $2 $3 $4 $5 $6 $7 $8 $9
bash/cblclg zcobol/tests/TESTCMP2 $1 $2 $3 $4 $5 $6 $7 $8 $9
bash/cblclg zcobol/tests/TESTCMP3 $1 $2 $3 $4 $5 $6 $7 $8 $9
bash/cblclg zcobol/tests/TESTCMP4 $1 $2 $3 $4 $5 $6 $7 $8 $9
bash/cblclg zcobol/tests/TESTCMP5 $1 $2 $3 $4 $5 $6 $7 $8 $9
bash/cblclg zcobol/tests/TESTCMP6 $1 $2 $3 $4 $5 $6 $7 $8 $9
bash/cblclg zcobol/tests/TESTCPY1 $1 $2 $3 $4 $5 $6 $7 $8 $9
bash/cblclg zcobol/tests/TESTCPY2 $1 $2 $3 $4 $5 $6 $7 $8 $9
bash/cblclg zcobol/tests/TESTDFP1 $1 $2 $3 $4 $5 $6 $7 $8 $9
bash/cblclg zcobol/tests/TESTDIV1 $1 $2 $3 $4 $5 $6 $7 $8 $9
bash/cblclg zcobol/tests/TESTDIV2 $1 $2 $3 $4 $5 $6 $7 $8 $9
bash/cblclg zcobol/tests/TESTDSP1 $1 $2 $3 $4 $5 $6 $7 $8 $9
export INFILE=zcobol/tests/TESTFIL1.IN
export OUTFILE=zcobol/tests/TESTFIL1.OUT
bash/cblclg zcobol/tests/TESTFIL1 $1 $2 $3 $4 $5 $6 $7 $8 $9
export INFILE=zcobol/tests/TESTFIL2.IN
export OUTFILE=zcobol/tests/TESTFIL2.OUT
bash/cblclg zcobol/tests/TESTFIL2 $1 $2 $3 $4 $5 $6 $7 $8 $9
export INFILE=
export OUTFILE=
bash/cblclg zcobol/tests/TESTGO1  $1 $2 $3 $4 $5 $6 $7 $8 $9
bash/cblclg zcobol/tests/TESTHFP1 $1 $2 $3 $4 $5 $6 $7 $8 $9
bash/cblclg zcobol/tests/TESTISP1 $1 $2 $3 $4 $5 $6 $7 $8 $9
bash/cblclg zcobol/tests/TESTPIC1 $1 $2 $3 $4 $5 $6 $7 $8 $9
bash/cblclg zcobol/tests/TESTPM1  $1 $2 $3 $4 $5 $6 $7 $8 $9
bash/cblclg zcobol/tests/TESTPM2  $1 $2 $3 $4 $5 $6 $7 $8 $9
export INFILE=zcobol/tests/TESTPM3.IN
export OUTFILE=zcobol/tests/TESTPM3.OUT
bash/cblclg zcobol/tests/TESTPM3  $1 $2 $3 $4 $5 $6 $7 $8 $9
export INFILE=
export OUTFILE=
bash/cblclg zcobol/tests/TESTSIX1 $1 $2 $3 $4 $5 $6 $7 $8 $9
bash/cblclg zcobol/tests/TESTSIX2 $1 $2 $3 $4 $5 $6 $7 $8 $9
bash/cblclg zcobol/tests/TESTSUB1 $1 $2 $3 $4 $5 $6 $7 $8 $9
bash/cblclg zcobol/tests/TESTSUB2 $1 $2 $3 $4 $5 $6 $7 $8 $9
bash/cblclg zcobol/tests/TESTTRC1 $1 $2 $3 $4 $5 $6 $7 $8 $9 TRUNC
bash/cblclg zcobol/tests/TESTTRC2 $1 $2 $3 $4 $5 $6 $7 $8 $9 
bash/cblclg zcobol/tests/TESTTRC3 $1 $2 $3 $4 $5 $6 $7 $8 $9 TRUNC NOR64
bash/cblclg zcobol/tests/TESTWS1  $1 $2 $3 $4 $5 $6 $7 $8 $9

bash/cblclg zcobol/tests/TESTBFP1 $1 $2 $3 $4 $5 $6 $7 $8 $9
bash/cblclg zcobol/tests/TESTIF1 $1 $2 $3 $4 $5 $6 $7 $8 $9
bash/cblclg zcobol/tests/TESTIF2 $1 $2 $3 $4 $5 $6 $7 $8 $9
bash/cblclg zcobol/tests/TESTIF3 $1 $2 $3 $4 $5 $6 $7 $8 $9
bash/cblclg zcobol/tests/TESTMOV1 $1 $2 $3 $4 $5 $6 $7 $8 $9
bash/cblclg zcobol/tests/TESTMOV2 $1 $2 $3 $4 $5 $6 $7 $8 $9
bash/cblclg zcobol/tests/TESTMOV3 $1 $2 $3 $4 $5 $6 $7 $8 $9
bash/cblclg zcobol/tests/CM101M01 $1 $2 $3 $4 $5 $6 $7 $8 $9
bash/cblc   zcobol/tests/CM101M03 $1 $2 $3 $4 $5 $6 $7 $8 $9
bash/cblclg zcobol/tests/DB101A01 $1 $2 $3 $4 $5 $6 $7 $8 $9
bash/cblclg zcobol/tests/NC106A01 $1 $2 $3 $4 $5 $6 $7 $8 $9
bash/cblclg zcobol/tests/TESTREPL $1 $2 $3 $4 $5 $6 $7 $8 $9
bash/cblclg zcobol/tests/YOUZPI1 $1 $2 $3 $4 $5 $6 $7 $8 $9
export INFILE=zcobol/tests/SORTASC.TF1
export OUTFILE=zcobol/tests/SORTASC.OUT
bash/cblclg zcobol/tests/SORTASC $1 $2 $3 $4 $5 $6 $7 $8 $9
diff zcobol/tests/SORTASC.OUT zcobol/tests/SORTASC.TF2 || exit 1
export INFILE=zcobol/tests/SORTDEF.TF1
export OUTFILE=zcobol/tests/SORTDEF.OUT
bash/cblclg zcobol/tests/SORTDEF $1 $2 $3 $4 $5 $6 $7 $8 $9
diff zcobol/tests/SORTDEF.OUT zcobol/tests/SORTDEF.TF2 || exit 1
export INFILE=zcobol/tests/SORTPROC.TF1
export OUTFILE=zcobol/tests/SORTPROC.OUT
bash/cblclg zcobol/tests/SORTPROC $1 $2 $3 $4 $5 $6 $7 $8 $9
diff zcobol/tests/SORTPROC.OUT zcobol/tests/SORTPROC.TF2 || exit 1
export INFILE=zcobol/tests/SORTMULT.TF1
export ASCFILE=zcobol/tests/SORTMULT_ASC.OUT
export DESCFILE=zcobol/tests/SORTMULT_DSC.OUT
bash/cblclg zcobol/tests/SORTMULT $1 $2 $3 $4 $5 $6 $7 $8 $9
diff zcobol/tests/SORTMULT_ASC.OUT zcobol/tests/SORTMULT_ASC.TF2 || exit 1
diff zcobol/tests/SORTMULT_DSC.OUT zcobol/tests/SORTMULT_DSC.TF2 || exit 1
export INFILE=
export OUTFILE=
export ASCFILE=
export DESCFILE=

# if we get here, there were no errors
echo "Verify ZCOBOL regression tests ran without errors"
exit 0
