#!/bin/bash

# runmfacc: Run the MainFrame Assembler Coding Contest solution programs
set -e              # exit on all errors
cd $(dirname $0)    # set to directory of script - rt/bash
cd ..               # up to rt
cd ..               # up to z390

sysmac='sysmac(mac)'
optable='optable(z390)'

# For now: assembling and running; not validating output SNAP content
# rem EXSAMPL2 and P20WR1 abend when executed
bash/asml  mfacc/EXSAMPL2
bash/asmlg mfacc/P1C1
bash/asmlg mfacc/P1DSH1
bash/asmlg mfacc/P1DSH1A
bash/asmlg mfacc/P1RAFA1
bash/asmlg mfacc/P2MD1
bash/asmlg mfacc/P3DW1
bash/asmlg mfacc/P3LKM1
bash/asmlg mfacc/P3MM1
bash/asmlg mfacc/P4AN1
bash/asmlg mfacc/P4APN2
bash/asmlg mfacc/P4DSH1
bash/asmlg mfacc/P4DW1
bash/asmlg mfacc/P4RAFA1
bash/asmlg mfacc/P4RAFA2
bash/asmlg mfacc/P4RJ1
bash/asmlg mfacc/P5DW1
bash/asmlg mfacc/P5MM1
bash/asmlg mfacc/P6BR1
bash/asmlg mfacc/P6MM1
bash/asmlg mfacc/P6PJF1
bash/asmlg mfacc/P6PL1
bash/asmlg mfacc/P6RW1
bash/asmlg mfacc/P7DSH1
bash/asmlg mfacc/P7EH1
bash/asmlg mfacc/P7RV1
bash/asmlg mfacc/P8DSH1
bash/asmlg mfacc/P8DSH2
bash/asmlg mfacc/P8LM1
bash/asmlg mfacc/P8MM1
bash/asmlg mfacc/P9DSH1
bash/asmlg mfacc/P9MM1
bash/asmlg mfacc/P9MM2
bash/asmlg mfacc/P10DSH1
bash/asmlg mfacc/P10DSH2
bash/asmlg mfacc/P10MB1
bash/asmlg mfacc/P11DSH1
bash/asmlg mfacc/P11DSH2
bash/asmlg mfacc/P11DW1
bash/asmlg mfacc/P11FIND1
bash/asmlg mfacc/P11FIND2
bash/asmlg mfacc/P11MODEL
bash/asmlg mfacc/P11WR1
bash/asmlg mfacc/P12DSH1
bash/asmlg mfacc/P12DSH2
bash/asmlg mfacc/P12DSH3
bash/asmlg mfacc/P13DSH1
bash/asmlg mfacc/P13SC1
bash/asmlg mfacc/P14DSH1
bash/asmlg mfacc/P14MW1
bash/asmlg mfacc/P15DSH1
bash/asmlg mfacc/P15WR1
export SYSOUT=mfacc/P16AFK1.OUT
bash/asmlg mfacc/P16AFK1
bash/asmlg mfacc/P16DSH1
bash/asmlg mfacc/P16WR1
bash/asmlg mfacc/P17DW1
bash/asmlg mfacc/P17WR1
bash/asmlg mfacc/P18DSH1
bash/asmlg mfacc/P19WR1
bash/asml  mfacc/P20WR1
bash/asmlg mfacc/P21DW1
bash/asmlg mfacc/P22DSH1
bash/asmlg mfacc/P22FS1
bash/asmlg mfacc/P22GH1
bash/asmlg mfacc/P22MM1
bash/asmlg mfacc/P22RL1

# if we get here, there were no errors
echo "MFACC tests ran without errors"
exit 0
