#!/bin/bash

# runmvstests: Run the MVS demo and test programs
set -e              # exit on all errors
cd $(dirname $0)    # set to directory of script - rt/bash
cd ..               # up to rt
cd ..               # up to z390

bash/asmlg mvs/demo/DEMO     notiming stats bal noloadhigh sysmac(mac)
bash/asm   mvs/test/TESTCVTX notiming stats bal noloadhigh sysmac(mac)
bash/asmlg mvs/test/TESTCVT1 notiming stats bal noloadhigh sysmac(mvs/maclib+mac)
bash/asmlg mvs/test/TESTMVS1 notiming stats bal noloadhigh sysmac(mvs/maclib+mac)

# if we get here, there were no errors
echo "MVS tests ran without errors"
exit 0
