#!/bin/bash

# runrtbsam: run RT QSAM for V,VB,VT,VL
# BLD? creates test file
# CHK? verifies test file
# See the trace files for snap dumps of records
#
# If one of the BLD* steps times out, run with NOTIME:
#     $ ./runrtqsam notime
#
set -e              # exit on all errors
cd $(dirname $0)    # set to directory of script - rt/bash
cd ..               # up to rt
cd ..               # up to z390

shopt -s nullglob
for f in bsam/BLD*.ERR; do
    if [ -f "$f" ]; then rm "$f"; fi
done
shopt -u nullglob

shopt -s nullglob
for f in bsam/TEST*.TFV; do
    if [ -f "$f" ]; then rm "$f"; fi
done
shopt -u nullglob

export SNAPOUT=DUMMY
export SYSUT2=bsam/TESTW.TFV
bash/asmlg bsam/BLDW.MLC trace $1
export SYSUT1=bsam/TESTW.TFV
bash/asmlg bsam/CHKW.MLC trace

export SYSUT2=bsam/TESTWL.TFV
bash/asmlg bsam/BLDWL.MLC trace $1
export SYSUT1=bsam/TESTWL.TFV
bash/asmlg bsam/CHKWL.MLC trace

export SYSUT1=bsam/TESTW.TFV
export SYSUT2=bsam/CPYRW.VES
bash/asmlg bsam/CPYRW.MLC trace $1
export SYSUT1=bsam/TESTWL.TFV
export SYSUT2=bsam/CPYRWL.VES
bash/asmlg bsam/CPYRWL.MLC trace

ls bsam/TEST*.TFV

# if we get here, all tests ran without errors
exit 0
