#!/bin/bash

# runrtqsam: run RT QSAM for V,VB,VT,VL
# BLD? creates test file
# CHK? verifies test file
# See the trace files for snap dumps of records
#
# If one of the BLD* steps times out, run with NOTIME:
#     $ ./runrtqsam notime
#
set -e              # exit on all errors
cd $(dirname $0)    # set to directory of script - rt/bash
cd ..               # up to rt
cd ..               # up to z390

#if [ -f qsam/BLD*.ERR ]; then rm qsam/BLD*.ERR; fi
shopt -s nullglob
for f in qsam/BLD*.ERR; do
#    echo "remove file: $f"
    if [ -f "$f" ]; then rm "$f"; fi
done
shopt -u nullglob

#if [ -f qsam/TEST*.TFV ]; then rm qsam/TEST*.TFV; fi
shopt -s nullglob
for f in qsam/TEST*.TFV; do
#    echo "remove file: $f"
    if [ -f "$f" ]; then rm "$f"; fi
done
shopt -u nullglob

export SNAPOUT=DUMMY

export SYSUT2=qsam/TESTV.TFV
bash/asmlg qsam/BLDV.MLC trace $1
export SYSUT1=qsam/TESTV.TFV
bash/asmlg qsam/CHKV.MLC trace $1

export SYSUT2=qsam/TESTVB.TFV
bash/asmlg qsam/BLDVB.MLC trace $1
export SYSUT1=qsam/TESTVB.TFV
bash/asmlg qsam/CHKVB.MLC trace $1

export SYSUT2=qsam/TESTVT.TFV
bash/asmlg qsam/BLDVT.MLC trace $1
export SYSUT1=qsam/TESTVT.TFV
bash/asmlg qsam/CHKVT.MLC trace $1

export SYSUT2=qsam/TESTVL.TFV
bash/asmlg qsam/BLDVL.MLC trace $1
export SYSUT1=qsam/TESTVL.TFV
bash/asmlg qsam/CHKVL.MLC trace $1

export SYSUT2=qsam/TESTVBL.TFV
bash/asmlg qsam/BLDVBL.MLC trace $1
export SYSUT1=qsam/TESTVBL.TFV
bash/asmlg qsam/CHKVBL.MLC trace $1

export SYSUT2=qsam/TESTVTL.TFV
bash/asmlg qsam/BLDVTL.MLC trace $1
export SYSUT1=qsam/TESTVTL.TFV
bash/asmlg qsam/CHKVTL.MLC trace $1

export SYSUT2=qsam/TESTF.TFV
bash/asmlg qsam/BLDF.MLC trace $1
export SYSUT1=qsam/TESTF.TFV
bash/asmlg qsam/CHKF.MLC trace $1

export SYSUT2=qsam/TESTFL.TFV
bash/asmlg qsam/BLDFL.MLC trace $1
export SYSUT1=qsam/TESTFL.TFV
bash/asmlg qsam/CHKFL.MLC trace $1

export SYSUT2=qsam/TESTFT.TFV
bash/asmlg qsam/BLDFT.MLC trace $1
export SYSUT1=qsam/TESTFT.TFV
bash/asmlg qsam/CHKFT.MLC trace $1

export SYSUT2=qsam/TESTFTL.TFV
bash/asmlg qsam/BLDFTL.MLC trace $1
export SYSUT1=qsam/TESTFTL.TFV
bash/asmlg qsam/CHKFTL.MLC trace $1

ls qsam/TEST*.TFV

# if we get here, there were no errors
exit 0
