#!/bin/bash

# runasmtests: regression test z390 instructions
# 2022-05-07 DSH add TESTDC1-3, TESTASC1 tests for #233 blanks in DC nominal values
set -e              # exit on all errors
cd $(dirname $0)    # set to directory of script - rt/bash
cd ..               # up to rt
cd ..               # up to z390

sysmac='sysmac(mac)'
vsam='zvsam(2)'

vsam2/bash/runtests

# if we get here, there were no errors
echo "Verify tests ran without errors"
exit 0
