#!/bin/bash

# runasmtests: regression test z390 instructions
# 2022-05-07 DSH add TESTDC1-3, TESTASC1 tests for #233 blanks in DC nominal values
set -e              # exit on all errors
cd $(dirname $0)    # set to directory of script - rt/bash
cd ..               # up to rt
cd ..               # up to z390

sysmac='sysmac(mac)'
vsam='zvsam(2)'

bash/asml  vsam2/mlc/Z390CAT2 $sysmac $vsam
bash/asml  vsam2/mlc/ZVSAM19C $sysmac $vsam
bash/asml  vsam2/mlc/TESTGNCB $sysmac $vsam
bash/asml  vsam2/mlc/TESTMDCB $sysmac $vsam
bash/asml  vsam2/mlc/TESTSHCB $sysmac $vsam
bash/asml  vsam2/mlc/TESTTSCB $sysmac $vsam

# if we get here, there were no errors
echo "Verify tests ran without errors"
exit 0
