#!/bin/bash

# runzpar: run ZPAR asm and cbl demos
#
set -e              # exit on all errors
cd $(dirname $0)    # set to directory of script - rt/bash
cd ..               # up to rt
cd ..               # up to z390


bash/asmlg demo/HELLO trace

sysparm="SYSPARM(demo/HELLO)"
bash/mac zpar/ZPARTRS $sysparm

bash/cblclg zcobol/demo/HELLO trace

sysparm="SYSPARM(zcobol/demo/HELLO)"
bash/mac zpar/ZPARTRS $sysparm

# done with tests
# if we get here, there were no errors
echo "See generated TRS files to verify ZPAR demos ok"
exit 0
