SET CICSPATH=cics
SET ZC39PATH=zcobol\z390
SET PROGPATH=linklib
rem
rem SUBPROGRAMS
rem
SET PROGRAM=GBL0602
CALL MZ390 %CICSPATH%\%PROGRAM% SYSMAC(%CICSPATH%+MAC) SYSCPY(%CICSPATH%+MAC)
IF ERRORLEVEL 1 GOTO WRONG
SET PRNFILE=%CICSPATH%\%PROGRAM%.PRN
SET URFFILE=%CICSPATH%\%PROGRAM%.URF
CALL EZ390 %PROGPATH%\UNREF ASCII
IF ERRORLEVEL 1 GOTO WRONG

SET PROGRAM=GBL060C
CALL MZ390 %CICSPATH%\%PROGRAM% SYSMAC(%CICSPATH%+MAC) SYSCPY(%CICSPATH%+MAC)
IF ERRORLEVEL 1 GOTO WRONG
SET PRNFILE=%CICSPATH%\%PROGRAM%.PRN
SET URFFILE=%CICSPATH%\%PROGRAM%.URF
CALL EZ390 %PROGPATH%\UNREF ASCII
IF ERRORLEVEL 1 GOTO WRONG

SET PROGRAM=GBL060E
CALL MZ390 %CICSPATH%\%PROGRAM% SYSMAC(%CICSPATH%+MAC) SYSCPY(%CICSPATH%+MAC)
IF ERRORLEVEL 1 GOTO WRONG
SET PRNFILE=%CICSPATH%\%PROGRAM%.PRN
SET URFFILE=%CICSPATH%\%PROGRAM%.URF
CALL EZ390 %PROGPATH%\UNREF ASCII
IF ERRORLEVEL 1 GOTO WRONG

SET PROGRAM=GBL0610
CALL MZ390 %CICSPATH%\%PROGRAM% SYSMAC(%CICSPATH%+MAC) SYSCPY(%CICSPATH%+MAC)
IF ERRORLEVEL 1 GOTO WRONG
SET PRNFILE=%CICSPATH%\%PROGRAM%.PRN
SET URFFILE=%CICSPATH%\%PROGRAM%.URF
CALL EZ390 %PROGPATH%\UNREF ASCII
IF ERRORLEVEL 1 GOTO WRONG

SET PROGRAM=GBL0612
CALL MZ390 %CICSPATH%\%PROGRAM% SYSMAC(%CICSPATH%+MAC) SYSCPY(%CICSPATH%+MAC)
IF ERRORLEVEL 1 GOTO WRONG
SET PRNFILE=%CICSPATH%\%PROGRAM%.PRN
SET URFFILE=%CICSPATH%\%PROGRAM%.URF
CALL EZ390 %PROGPATH%\UNREF ASCII
IF ERRORLEVEL 1 GOTO WRONG

SET PROGRAM=GBL0614
CALL MZ390 %CICSPATH%\%PROGRAM% SYSMAC(%CICSPATH%+MAC) SYSCPY(%CICSPATH%+MAC)
IF ERRORLEVEL 1 GOTO WRONG
SET PRNFILE=%CICSPATH%\%PROGRAM%.PRN
SET URFFILE=%CICSPATH%\%PROGRAM%.URF
CALL EZ390 %PROGPATH%\UNREF ASCII
IF ERRORLEVEL 1 GOTO WRONG

SET PROGRAM=GBL0A02
CALL MZ390 %CICSPATH%\%PROGRAM% SYSMAC(%CICSPATH%+MAC) SYSCPY(%CICSPATH%+MAC)
IF ERRORLEVEL 1 GOTO WRONG
SET PRNFILE=%CICSPATH%\%PROGRAM%.PRN
SET URFFILE=%CICSPATH%\%PROGRAM%.URF
CALL EZ390 %PROGPATH%\UNREF ASCII
IF ERRORLEVEL 1 GOTO WRONG

SET PROGRAM=GBL0A04
CALL MZ390 %CICSPATH%\%PROGRAM% SYSMAC(%CICSPATH%+MAC) SYSCPY(%CICSPATH%+MAC)
IF ERRORLEVEL 1 GOTO WRONG
SET PRNFILE=%CICSPATH%\%PROGRAM%.PRN
SET URFFILE=%CICSPATH%\%PROGRAM%.URF
CALL EZ390 %PROGPATH%\UNREF ASCII
IF ERRORLEVEL 1 GOTO WRONG

SET PROGRAM=GBL0A06
CALL MZ390 %CICSPATH%\%PROGRAM% SYSMAC(%CICSPATH%+MAC) SYSCPY(%CICSPATH%+MAC)
IF ERRORLEVEL 1 GOTO WRONG
SET PRNFILE=%CICSPATH%\%PROGRAM%.PRN
SET URFFILE=%CICSPATH%\%PROGRAM%.URF
CALL EZ390 %PROGPATH%\UNREF ASCII
IF ERRORLEVEL 1 GOTO WRONG

SET PROGRAM=GBL0AFF
CALL MZ390 %CICSPATH%\%PROGRAM% SYSMAC(%CICSPATH%+MAC) SYSCPY(%CICSPATH%+MAC)
IF ERRORLEVEL 1 GOTO WRONG
SET PRNFILE=%CICSPATH%\%PROGRAM%.PRN
SET URFFILE=%CICSPATH%\%PROGRAM%.URF
CALL EZ390 %PROGPATH%\UNREF ASCII
IF ERRORLEVEL 1 GOTO WRONG

SET PROGRAM=GBL1004
CALL MZ390 %CICSPATH%\%PROGRAM% SYSMAC(%CICSPATH%+MAC) SYSCPY(%CICSPATH%+MAC)
IF ERRORLEVEL 1 GOTO WRONG
SET PRNFILE=%CICSPATH%\%PROGRAM%.PRN
SET URFFILE=%CICSPATH%\%PROGRAM%.URF
CALL EZ390 %PROGPATH%\UNREF ASCII
IF ERRORLEVEL 1 GOTO WRONG

SET PROGRAM=GBL1008
CALL MZ390 %CICSPATH%\%PROGRAM% SYSMAC(%CICSPATH%+MAC) SYSCPY(%CICSPATH%+MAC)
IF ERRORLEVEL 1 GOTO WRONG
SET PRNFILE=%CICSPATH%\%PROGRAM%.PRN
SET URFFILE=%CICSPATH%\%PROGRAM%.URF
CALL EZ390 %PROGPATH%\UNREF ASCII
IF ERRORLEVEL 1 GOTO WRONG

SET PROGRAM=GBL100C
CALL MZ390 %CICSPATH%\%PROGRAM% SYSMAC(%CICSPATH%+MAC) SYSCPY(%CICSPATH%+MAC)
IF ERRORLEVEL 1 GOTO WRONG
SET PRNFILE=%CICSPATH%\%PROGRAM%.PRN
SET URFFILE=%CICSPATH%\%PROGRAM%.URF
CALL EZ390 %PROGPATH%\UNREF ASCII
IF ERRORLEVEL 1 GOTO WRONG

SET PROGRAM=GBL10FF
CALL MZ390 %CICSPATH%\%PROGRAM% SYSMAC(%CICSPATH%+MAC) SYSCPY(%CICSPATH%+MAC)
IF ERRORLEVEL 1 GOTO WRONG
SET PRNFILE=%CICSPATH%\%PROGRAM%.PRN
SET URFFILE=%CICSPATH%\%PROGRAM%.URF
CALL EZ390 %PROGPATH%\UNREF ASCII
IF ERRORLEVEL 1 GOTO WRONG

SET PROGRAM=GBL1204
CALL MZ390 %CICSPATH%\%PROGRAM% SYSMAC(%CICSPATH%+MAC) SYSCPY(%CICSPATH%+MAC)
IF ERRORLEVEL 1 GOTO WRONG
SET PRNFILE=%CICSPATH%\%PROGRAM%.PRN
SET URFFILE=%CICSPATH%\%PROGRAM%.URF
CALL EZ390 %PROGPATH%\UNREF ASCII
IF ERRORLEVEL 1 GOTO WRONG

SET PROGRAM=GBL1206
CALL MZ390 %CICSPATH%\%PROGRAM% SYSMAC(%CICSPATH%+MAC) SYSCPY(%CICSPATH%+MAC)
IF ERRORLEVEL 1 GOTO WRONG
SET PRNFILE=%CICSPATH%\%PROGRAM%.PRN
SET URFFILE=%CICSPATH%\%PROGRAM%.URF
CALL EZ390 %PROGPATH%\UNREF ASCII
IF ERRORLEVEL 1 GOTO WRONG

SET PROGRAM=GBL12FC
CALL MZ390 %CICSPATH%\%PROGRAM% SYSMAC(%CICSPATH%+MAC) SYSCPY(%CICSPATH%+MAC)
IF ERRORLEVEL 1 GOTO WRONG
SET PRNFILE=%CICSPATH%\%PROGRAM%.PRN
SET URFFILE=%CICSPATH%\%PROGRAM%.URF
CALL EZ390 %PROGPATH%\UNREF ASCII
IF ERRORLEVEL 1 GOTO WRONG

SET PROGRAM=GBL4C02
CALL MZ390 %CICSPATH%\%PROGRAM% SYSMAC(%CICSPATH%+MAC) SYSCPY(%CICSPATH%+MAC)
IF ERRORLEVEL 1 GOTO WRONG
SET PRNFILE=%CICSPATH%\%PROGRAM%.PRN
SET URFFILE=%CICSPATH%\%PROGRAM%.URF
CALL EZ390 %PROGPATH%\UNREF ASCII
IF ERRORLEVEL 1 GOTO WRONG

SET PROGRAM=GBL4C04
CALL MZ390 %CICSPATH%\%PROGRAM% SYSMAC(%CICSPATH%+MAC) SYSCPY(%CICSPATH%+MAC)
IF ERRORLEVEL 1 GOTO WRONG
SET PRNFILE=%CICSPATH%\%PROGRAM%.PRN
SET URFFILE=%CICSPATH%\%PROGRAM%.URF
CALL EZ390 %PROGPATH%\UNREF ASCII
IF ERRORLEVEL 1 GOTO WRONG

SET PROGRAM=GBLFE00
CALL MZ390 %CICSPATH%\%PROGRAM% SYSMAC(%CICSPATH%+MAC) SYSCPY(%CICSPATH%+MAC)
IF ERRORLEVEL 1 GOTO WRONG
SET PRNFILE=%CICSPATH%\%PROGRAM%.PRN
SET URFFILE=%CICSPATH%\%PROGRAM%.URF
CALL EZ390 %PROGPATH%\UNREF ASCII
IF ERRORLEVEL 1 GOTO WRONG

SET PROGRAM=GBLFE01
CALL MZ390 %CICSPATH%\%PROGRAM% SYSMAC(%CICSPATH%+MAC) SYSCPY(%CICSPATH%+MAC)
IF ERRORLEVEL 1 GOTO WRONG
SET PRNFILE=%CICSPATH%\%PROGRAM%.PRN
SET URFFILE=%CICSPATH%\%PROGRAM%.URF
CALL EZ390 %PROGPATH%\UNREF ASCII
IF ERRORLEVEL 1 GOTO WRONG

SET PROGRAM=GBLFE06
CALL MZ390 %CICSPATH%\%PROGRAM% SYSMAC(%CICSPATH%+MAC) SYSCPY(%CICSPATH%+MAC)
IF ERRORLEVEL 1 GOTO WRONG
SET PRNFILE=%CICSPATH%\%PROGRAM%.PRN
SET URFFILE=%CICSPATH%\%PROGRAM%.URF
CALL EZ390 %PROGPATH%\UNREF ASCII
IF ERRORLEVEL 1 GOTO WRONG

SET PROGRAM=GBLFE07
CALL MZ390 %CICSPATH%\%PROGRAM% SYSMAC(%CICSPATH%+MAC) SYSCPY(%CICSPATH%+MAC)
IF ERRORLEVEL 1 GOTO WRONG
SET PRNFILE=%CICSPATH%\%PROGRAM%.PRN
SET URFFILE=%CICSPATH%\%PROGRAM%.URF
CALL EZ390 %PROGPATH%\UNREF ASCII
IF ERRORLEVEL 1 GOTO WRONG

SET PROGRAM=LCL0202
CALL MZ390 %CICSPATH%\%PROGRAM% NOEDF SYSMAC(%CICSPATH%+MAC) SYSCPY(%CICSPATH%+MAC)
IF ERRORLEVEL 1 GOTO WRONG
SET PRNFILE=%CICSPATH%\%PROGRAM%.PRN
SET URFFILE=%CICSPATH%\%PROGRAM%.URF
CALL EZ390 %PROGPATH%\UNREF ASCII
IF ERRORLEVEL 1 GOTO WRONG

SET PROGRAM=LCL0204
CALL MZ390 %CICSPATH%\%PROGRAM% SYSMAC(%CICSPATH%+MAC) SYSCPY(%CICSPATH%+MAC)
IF ERRORLEVEL 1 GOTO WRONG
SET PRNFILE=%CICSPATH%\%PROGRAM%.PRN
SET URFFILE=%CICSPATH%\%PROGRAM%.URF
CALL EZ390 %PROGPATH%\UNREF ASCII
IF ERRORLEVEL 1 GOTO WRONG

SET PROGRAM=LCL0206
CALL MZ390 %CICSPATH%\%PROGRAM% SYSMAC(%CICSPATH%+MAC) SYSCPY(%CICSPATH%+MAC)
IF ERRORLEVEL 1 GOTO WRONG
SET PRNFILE=%CICSPATH%\%PROGRAM%.PRN
SET URFFILE=%CICSPATH%\%PROGRAM%.URF
CALL EZ390 %PROGPATH%\UNREF ASCII
IF ERRORLEVEL 1 GOTO WRONG

SET PROGRAM=LCL0208
CALL MZ390 %CICSPATH%\%PROGRAM% SYSMAC(%CICSPATH%+MAC) SYSCPY(%CICSPATH%+MAC)
IF ERRORLEVEL 1 GOTO WRONG
SET PRNFILE=%CICSPATH%\%PROGRAM%.PRN
SET URFFILE=%CICSPATH%\%PROGRAM%.URF
CALL EZ390 %PROGPATH%\UNREF ASCII
IF ERRORLEVEL 1 GOTO WRONG

SET PROGRAM=LCL020A
CALL MZ390 %CICSPATH%\%PROGRAM% SYSMAC(%CICSPATH%+MAC) SYSCPY(%CICSPATH%+MAC)
IF ERRORLEVEL 1 GOTO WRONG
SET PRNFILE=%CICSPATH%\%PROGRAM%.PRN
SET URFFILE=%CICSPATH%\%PROGRAM%.URF
CALL EZ390 %PROGPATH%\UNREF ASCII
IF ERRORLEVEL 1 GOTO WRONG

SET PROGRAM=LCL020C
CALL MZ390 %CICSPATH%\%PROGRAM% SYSMAC(%CICSPATH%+MAC) SYSCPY(%CICSPATH%+MAC)
IF ERRORLEVEL 1 GOTO WRONG
SET PRNFILE=%CICSPATH%\%PROGRAM%.PRN
SET URFFILE=%CICSPATH%\%PROGRAM%.URF
CALL EZ390 %PROGPATH%\UNREF ASCII
IF ERRORLEVEL 1 GOTO WRONG

SET PROGRAM=LCL020E
CALL MZ390 %CICSPATH%\%PROGRAM% SYSMAC(%CICSPATH%+MAC) SYSCPY(%CICSPATH%+MAC)
IF ERRORLEVEL 1 GOTO WRONG
SET PRNFILE=%CICSPATH%\%PROGRAM%.PRN
SET URFFILE=%CICSPATH%\%PROGRAM%.URF
CALL EZ390 %PROGPATH%\UNREF ASCII
IF ERRORLEVEL 1 GOTO WRONG

SET PROGRAM=LCL0402
CALL MZ390 %CICSPATH%\%PROGRAM% SYSMAC(%CICSPATH%+MAC) SYSCPY(%CICSPATH%+MAC)
IF ERRORLEVEL 1 GOTO WRONG
SET PRNFILE=%CICSPATH%\%PROGRAM%.PRN
SET URFFILE=%CICSPATH%\%PROGRAM%.URF
CALL EZ390 %PROGPATH%\UNREF ASCII
IF ERRORLEVEL 1 GOTO WRONG

SET PROGRAM=LCL0404
CALL MZ390 %CICSPATH%\%PROGRAM% SYSMAC(%CICSPATH%+MAC) SYSCPY(%CICSPATH%+MAC)
IF ERRORLEVEL 1 GOTO WRONG
SET PRNFILE=%CICSPATH%\%PROGRAM%.PRN
SET URFFILE=%CICSPATH%\%PROGRAM%.URF
CALL EZ390 %PROGPATH%\UNREF ASCII
IF ERRORLEVEL 1 GOTO WRONG

SET PROGRAM=LCL0602
CALL MZ390 %CICSPATH%\%PROGRAM% NOEDF SYSMAC(%CICSPATH%+MAC) SYSCPY(%CICSPATH%+MAC)
IF ERRORLEVEL 1 GOTO WRONG
SET PRNFILE=%CICSPATH%\%PROGRAM%.PRN
SET URFFILE=%CICSPATH%\%PROGRAM%.URF
CALL EZ390 %PROGPATH%\UNREF ASCII
IF ERRORLEVEL 1 GOTO WRONG

SET PROGRAM=LCL060C
CALL MZ390 %CICSPATH%\%PROGRAM% NOEDF SYSMAC(%CICSPATH%+MAC) SYSCPY(%CICSPATH%+MAC)
IF ERRORLEVEL 1 GOTO WRONG
SET PRNFILE=%CICSPATH%\%PROGRAM%.PRN
SET URFFILE=%CICSPATH%\%PROGRAM%.URF
CALL EZ390 %PROGPATH%\UNREF ASCII
IF ERRORLEVEL 1 GOTO WRONG

SET PROGRAM=LCL060E
CALL MZ390 %CICSPATH%\%PROGRAM% NOEDF SYSMAC(%CICSPATH%+MAC) SYSCPY(%CICSPATH%+MAC)
IF ERRORLEVEL 1 GOTO WRONG
SET PRNFILE=%CICSPATH%\%PROGRAM%.PRN
SET URFFILE=%CICSPATH%\%PROGRAM%.URF
CALL EZ390 %PROGPATH%\UNREF ASCII
IF ERRORLEVEL 1 GOTO WRONG

SET PROGRAM=LCL0610
CALL MZ390 %CICSPATH%\%PROGRAM% NOEDF SYSMAC(%CICSPATH%+MAC) SYSCPY(%CICSPATH%+MAC)
IF ERRORLEVEL 1 GOTO WRONG
SET PRNFILE=%CICSPATH%\%PROGRAM%.PRN
SET URFFILE=%CICSPATH%\%PROGRAM%.URF
CALL EZ390 %PROGPATH%\UNREF ASCII
IF ERRORLEVEL 1 GOTO WRONG

SET PROGRAM=LCL0612
CALL MZ390 %CICSPATH%\%PROGRAM% NOEDF SYSMAC(%CICSPATH%+MAC) SYSCPY(%CICSPATH%+MAC)
IF ERRORLEVEL 1 GOTO WRONG
SET PRNFILE=%CICSPATH%\%PROGRAM%.PRN
SET URFFILE=%CICSPATH%\%PROGRAM%.URF
CALL EZ390 %PROGPATH%\UNREF ASCII
IF ERRORLEVEL 1 GOTO WRONG

SET PROGRAM=LCL0614
CALL MZ390 %CICSPATH%\%PROGRAM% NOEDF SYSMAC(%CICSPATH%+MAC) SYSCPY(%CICSPATH%+MAC)
IF ERRORLEVEL 1 GOTO WRONG
SET PRNFILE=%CICSPATH%\%PROGRAM%.PRN
SET URFFILE=%CICSPATH%\%PROGRAM%.URF
CALL EZ390 %PROGPATH%\UNREF ASCII
IF ERRORLEVEL 1 GOTO WRONG

SET PROGRAM=LCL0A02
CALL MZ390 %CICSPATH%\%PROGRAM% NOEDF SYSMAC(%CICSPATH%+MAC) SYSCPY(%CICSPATH%+MAC)
IF ERRORLEVEL 1 GOTO WRONG
SET PRNFILE=%CICSPATH%\%PROGRAM%.PRN
SET URFFILE=%CICSPATH%\%PROGRAM%.URF
CALL EZ390 %PROGPATH%\UNREF ASCII
IF ERRORLEVEL 1 GOTO WRONG

SET PROGRAM=LCL0A04
CALL MZ390 %CICSPATH%\%PROGRAM% NOEDF SYSMAC(%CICSPATH%+MAC) SYSCPY(%CICSPATH%+MAC)
IF ERRORLEVEL 1 GOTO WRONG
SET PRNFILE=%CICSPATH%\%PROGRAM%.PRN
SET URFFILE=%CICSPATH%\%PROGRAM%.URF
CALL EZ390 %PROGPATH%\UNREF ASCII
IF ERRORLEVEL 1 GOTO WRONG

SET PROGRAM=LCL0A06
CALL MZ390 %CICSPATH%\%PROGRAM% NOEDF SYSMAC(%CICSPATH%+MAC) SYSCPY(%CICSPATH%+MAC)
IF ERRORLEVEL 1 GOTO WRONG
SET PRNFILE=%CICSPATH%\%PROGRAM%.PRN
SET URFFILE=%CICSPATH%\%PROGRAM%.URF
CALL EZ390 %PROGPATH%\UNREF ASCII
IF ERRORLEVEL 1 GOTO WRONG

SET PROGRAM=LCL0C02
CALL MZ390 %CICSPATH%\%PROGRAM% SYSMAC(%CICSPATH%+MAC) SYSCPY(%CICSPATH%+MAC)
IF ERRORLEVEL 1 GOTO WRONG
SET PRNFILE=%CICSPATH%\%PROGRAM%.PRN
SET URFFILE=%CICSPATH%\%PROGRAM%.URF
CALL EZ390 %PROGPATH%\UNREF ASCII
IF ERRORLEVEL 1 GOTO WRONG

SET PROGRAM=LCL0C04
CALL MZ390 %CICSPATH%\%PROGRAM% SYSMAC(%CICSPATH%+MAC) SYSCPY(%CICSPATH%+MAC)
IF ERRORLEVEL 1 GOTO WRONG
SET PRNFILE=%CICSPATH%\%PROGRAM%.PRN
SET URFFILE=%CICSPATH%\%PROGRAM%.URF
CALL EZ390 %PROGPATH%\UNREF ASCII
IF ERRORLEVEL 1 GOTO WRONG

SET PROGRAM=LCL0E02
CALL MZ390 %CICSPATH%\%PROGRAM% SYSMAC(%CICSPATH%+MAC) SYSCPY(%CICSPATH%+MAC)
IF ERRORLEVEL 1 GOTO WRONG
SET PRNFILE=%CICSPATH%\%PROGRAM%.PRN
SET URFFILE=%CICSPATH%\%PROGRAM%.URF
CALL EZ390 %PROGPATH%\UNREF ASCII
IF ERRORLEVEL 1 GOTO WRONG

SET PROGRAM=LCL0E04
CALL MZ390 %CICSPATH%\%PROGRAM% SYSMAC(%CICSPATH%+MAC) SYSCPY(%CICSPATH%+MAC)
IF ERRORLEVEL 1 GOTO WRONG
SET PRNFILE=%CICSPATH%\%PROGRAM%.PRN
SET URFFILE=%CICSPATH%\%PROGRAM%.URF
CALL EZ390 %PROGPATH%\UNREF ASCII
IF ERRORLEVEL 1 GOTO WRONG

SET PROGRAM=LCL0E06
CALL MZ390 %CICSPATH%\%PROGRAM% SYSMAC(%CICSPATH%+MAC) SYSCPY(%CICSPATH%+MAC)
IF ERRORLEVEL 1 GOTO WRONG
SET PRNFILE=%CICSPATH%\%PROGRAM%.PRN
SET URFFILE=%CICSPATH%\%PROGRAM%.URF
CALL EZ390 %PROGPATH%\UNREF ASCII
IF ERRORLEVEL 1 GOTO WRONG

SET PROGRAM=LCL0E08
CALL MZ390 %CICSPATH%\%PROGRAM% SYSMAC(%CICSPATH%+MAC) SYSCPY(%CICSPATH%+MAC)
IF ERRORLEVEL 1 GOTO WRONG
SET PRNFILE=%CICSPATH%\%PROGRAM%.PRN
SET URFFILE=%CICSPATH%\%PROGRAM%.URF
CALL EZ390 %PROGPATH%\UNREF ASCII
IF ERRORLEVEL 1 GOTO WRONG

SET PROGRAM=LCL0E0A
CALL MZ390 %CICSPATH%\%PROGRAM% SYSMAC(%CICSPATH%+MAC) SYSCPY(%CICSPATH%+MAC)
IF ERRORLEVEL 1 GOTO WRONG
SET PRNFILE=%CICSPATH%\%PROGRAM%.PRN
SET URFFILE=%CICSPATH%\%PROGRAM%.URF
CALL EZ390 %PROGPATH%\UNREF ASCII
IF ERRORLEVEL 1 GOTO WRONG

SET PROGRAM=LCL0E0C
CALL MZ390 %CICSPATH%\%PROGRAM% SYSMAC(%CICSPATH%+MAC) SYSCPY(%CICSPATH%+MAC)
IF ERRORLEVEL 1 GOTO WRONG
SET PRNFILE=%CICSPATH%\%PROGRAM%.PRN
SET URFFILE=%CICSPATH%\%PROGRAM%.URF
CALL EZ390 %PROGPATH%\UNREF ASCII
IF ERRORLEVEL 1 GOTO WRONG

SET PROGRAM=LCL0E0E
CALL MZ390 %CICSPATH%\%PROGRAM% SYSMAC(%CICSPATH%+MAC) SYSCPY(%CICSPATH%+MAC)
IF ERRORLEVEL 1 GOTO WRONG
SET PRNFILE=%CICSPATH%\%PROGRAM%.PRN
SET URFFILE=%CICSPATH%\%PROGRAM%.URF
CALL EZ390 %PROGPATH%\UNREF ASCII
IF ERRORLEVEL 1 GOTO WRONG

SET PROGRAM=LCL1002
CALL MZ390 %CICSPATH%\%PROGRAM% SYSMAC(%CICSPATH%+MAC) SYSCPY(%CICSPATH%+MAC)
IF ERRORLEVEL 1 GOTO WRONG
SET PRNFILE=%CICSPATH%\%PROGRAM%.PRN
SET URFFILE=%CICSPATH%\%PROGRAM%.URF
CALL EZ390 %PROGPATH%\UNREF ASCII
IF ERRORLEVEL 1 GOTO WRONG

SET PROGRAM=LCL1004
CALL MZ390 %CICSPATH%\%PROGRAM% SYSMAC(%CICSPATH%+MAC) SYSCPY(%CICSPATH%+MAC)
IF ERRORLEVEL 1 GOTO WRONG
SET PRNFILE=%CICSPATH%\%PROGRAM%.PRN
SET URFFILE=%CICSPATH%\%PROGRAM%.URF
CALL EZ390 %PROGPATH%\UNREF ASCII
IF ERRORLEVEL 1 GOTO WRONG

SET PROGRAM=LCL1008
CALL MZ390 %CICSPATH%\%PROGRAM% NOEDF SYSMAC(%CICSPATH%+MAC) SYSCPY(%CICSPATH%+MAC)
IF ERRORLEVEL 1 GOTO WRONG
SET PRNFILE=%CICSPATH%\%PROGRAM%.PRN
SET URFFILE=%CICSPATH%\%PROGRAM%.URF
CALL EZ390 %PROGPATH%\UNREF ASCII
IF ERRORLEVEL 1 GOTO WRONG

SET PROGRAM=LCL100A
CALL MZ390 %CICSPATH%\%PROGRAM% NOEDF SYSMAC(%CICSPATH%+MAC) SYSCPY(%CICSPATH%+MAC)
IF ERRORLEVEL 1 GOTO WRONG
SET PRNFILE=%CICSPATH%\%PROGRAM%.PRN
SET URFFILE=%CICSPATH%\%PROGRAM%.URF
CALL EZ390 %PROGPATH%\UNREF ASCII
IF ERRORLEVEL 1 GOTO WRONG

SET PROGRAM=LCL100C
CALL MZ390 %CICSPATH%\%PROGRAM% SYSMAC(%CICSPATH%+MAC) SYSCPY(%CICSPATH%+MAC)
IF ERRORLEVEL 1 GOTO WRONG
SET PRNFILE=%CICSPATH%\%PROGRAM%.PRN
SET URFFILE=%CICSPATH%\%PROGRAM%.URF
CALL EZ390 %PROGPATH%\UNREF ASCII
IF ERRORLEVEL 1 GOTO WRONG

SET PROGRAM=LCL1204
CALL MZ390 %CICSPATH%\%PROGRAM% SYSMAC(%CICSPATH%+MAC) SYSCPY(%CICSPATH%+MAC)
IF ERRORLEVEL 1 GOTO WRONG
SET PRNFILE=%CICSPATH%\%PROGRAM%.PRN
SET URFFILE=%CICSPATH%\%PROGRAM%.URF
CALL EZ390 %PROGPATH%\UNREF ASCII
IF ERRORLEVEL 1 GOTO WRONG

SET PROGRAM=LCL1206
CALL MZ390 %CICSPATH%\%PROGRAM% SYSMAC(%CICSPATH%+MAC) SYSCPY(%CICSPATH%+MAC)
IF ERRORLEVEL 1 GOTO WRONG
SET PRNFILE=%CICSPATH%\%PROGRAM%.PRN
SET URFFILE=%CICSPATH%\%PROGRAM%.URF
CALL EZ390 %PROGPATH%\UNREF ASCII
IF ERRORLEVEL 1 GOTO WRONG

SET PROGRAM=LCL1802
CALL MZ390 %CICSPATH%\%PROGRAM% SYSMAC(%CICSPATH%+MAC) SYSCPY(%CICSPATH%+MAC)
IF ERRORLEVEL 1 GOTO WRONG
SET PRNFILE=%CICSPATH%\%PROGRAM%.PRN
SET URFFILE=%CICSPATH%\%PROGRAM%.URF
CALL EZ390 %PROGPATH%\UNREF ASCII
IF ERRORLEVEL 1 GOTO WRONG

SET PROGRAM=LCL1804
CALL MZ390 %CICSPATH%\%PROGRAM% SYSMAC(%CICSPATH%+MAC) SYSCPY(%CICSPATH%+MAC)
IF ERRORLEVEL 1 GOTO WRONG
SET PRNFILE=%CICSPATH%\%PROGRAM%.PRN
SET URFFILE=%CICSPATH%\%PROGRAM%.URF
CALL EZ390 %PROGPATH%\UNREF ASCII
IF ERRORLEVEL 1 GOTO WRONG

SET PROGRAM=LCL1812
CALL MZ390 %CICSPATH%\%PROGRAM% SYSMAC(%CICSPATH%+MAC) SYSCPY(%CICSPATH%+MAC)
IF ERRORLEVEL 1 GOTO WRONG
SET PRNFILE=%CICSPATH%\%PROGRAM%.PRN
SET URFFILE=%CICSPATH%\%PROGRAM%.URF
CALL EZ390 %PROGPATH%\UNREF ASCII
IF ERRORLEVEL 1 GOTO WRONG

SET PROGRAM=LCL1C02
CALL MZ390 %CICSPATH%\%PROGRAM% SYSMAC(%CICSPATH%+MAC) SYSCPY(%CICSPATH%+MAC)
IF ERRORLEVEL 1 GOTO WRONG
SET PRNFILE=%CICSPATH%\%PROGRAM%.PRN
SET URFFILE=%CICSPATH%\%PROGRAM%.URF
CALL EZ390 %PROGPATH%\UNREF ASCII
IF ERRORLEVEL 1 GOTO WRONG

SET PROGRAM=LCL3412
CALL MZ390 %CICSPATH%\%PROGRAM% NOEDF SYSMAC(%CICSPATH%+MAC) SYSCPY(%CICSPATH%+MAC)
IF ERRORLEVEL 1 GOTO WRONG
SET PRNFILE=%CICSPATH%\%PROGRAM%.PRN
SET URFFILE=%CICSPATH%\%PROGRAM%.URF
CALL EZ390 %PROGPATH%\UNREF ASCII
IF ERRORLEVEL 1 GOTO WRONG

SET PROGRAM=LCL3414
CALL MZ390 %CICSPATH%\%PROGRAM% NOEDF SYSMAC(%CICSPATH%+MAC) SYSCPY(%CICSPATH%+MAC)
IF ERRORLEVEL 1 GOTO WRONG
SET PRNFILE=%CICSPATH%\%PROGRAM%.PRN
SET URFFILE=%CICSPATH%\%PROGRAM%.URF
CALL EZ390 %PROGPATH%\UNREF ASCII
IF ERRORLEVEL 1 GOTO WRONG

SET PROGRAM=LCL3416
CALL MZ390 %CICSPATH%\%PROGRAM% NOEDF SYSMAC(%CICSPATH%+MAC) SYSCPY(%CICSPATH%+MAC)
IF ERRORLEVEL 1 GOTO WRONG
SET PRNFILE=%CICSPATH%\%PROGRAM%.PRN
SET URFFILE=%CICSPATH%\%PROGRAM%.URF
CALL EZ390 %PROGPATH%\UNREF ASCII
IF ERRORLEVEL 1 GOTO WRONG

SET PROGRAM=LCL3440
CALL MZ390 %CICSPATH%\%PROGRAM% NOEDF SYSMAC(%CICSPATH%+MAC) SYSCPY(%CICSPATH%+MAC)
IF ERRORLEVEL 1 GOTO WRONG
SET PRNFILE=%CICSPATH%\%PROGRAM%.PRN
SET URFFILE=%CICSPATH%\%PROGRAM%.URF
CALL EZ390 %PROGPATH%\UNREF ASCII
IF ERRORLEVEL 1 GOTO WRONG

SET PROGRAM=LCL4A02
CALL MZ390 %CICSPATH%\%PROGRAM% SYSMAC(%CICSPATH%+MAC) SYSCPY(%CICSPATH%+MAC)
IF ERRORLEVEL 1 GOTO WRONG
SET PRNFILE=%CICSPATH%\%PROGRAM%.PRN
SET URFFILE=%CICSPATH%\%PROGRAM%.URF
CALL EZ390 %PROGPATH%\UNREF ASCII
IF ERRORLEVEL 1 GOTO WRONG

SET PROGRAM=LCL4A04
CALL MZ390 %CICSPATH%\%PROGRAM% SYSMAC(%CICSPATH%+MAC) SYSCPY(%CICSPATH%+MAC)
IF ERRORLEVEL 1 GOTO WRONG
SET PRNFILE=%CICSPATH%\%PROGRAM%.PRN
SET URFFILE=%CICSPATH%\%PROGRAM%.URF
CALL EZ390 %PROGPATH%\UNREF ASCII
IF ERRORLEVEL 1 GOTO WRONG

SET PROGRAM=LCL4C02
CALL MZ390 %CICSPATH%\%PROGRAM% SYSMAC(%CICSPATH%+MAC) SYSCPY(%CICSPATH%+MAC)
IF ERRORLEVEL 1 GOTO WRONG
SET PRNFILE=%CICSPATH%\%PROGRAM%.PRN
SET URFFILE=%CICSPATH%\%PROGRAM%.URF
CALL EZ390 %PROGPATH%\UNREF ASCII
IF ERRORLEVEL 1 GOTO WRONG

SET PROGRAM=LCL4C04
CALL MZ390 %CICSPATH%\%PROGRAM% SYSMAC(%CICSPATH%+MAC) SYSCPY(%CICSPATH%+MAC)
IF ERRORLEVEL 1 GOTO WRONG
SET PRNFILE=%CICSPATH%\%PROGRAM%.PRN
SET URFFILE=%CICSPATH%\%PROGRAM%.URF
CALL EZ390 %PROGPATH%\UNREF ASCII
IF ERRORLEVEL 1 GOTO WRONG

SET PROGRAM=LCL9626
CALL MZ390 %CICSPATH%\%PROGRAM% SYSMAC(%CICSPATH%+MAC) SYSCPY(%CICSPATH%+MAC)
IF ERRORLEVEL 1 GOTO WRONG
SET PRNFILE=%CICSPATH%\%PROGRAM%.PRN
SET URFFILE=%CICSPATH%\%PROGRAM%.URF
CALL EZ390 %PROGPATH%\UNREF ASCII
IF ERRORLEVEL 1 GOTO WRONG

SET PROGRAM=LCL9628
CALL MZ390 %CICSPATH%\%PROGRAM% SYSMAC(%CICSPATH%+MAC) SYSCPY(%CICSPATH%+MAC)
IF ERRORLEVEL 1 GOTO WRONG
SET PRNFILE=%CICSPATH%\%PROGRAM%.PRN
SET URFFILE=%CICSPATH%\%PROGRAM%.URF
CALL EZ390 %PROGPATH%\UNREF ASCII
IF ERRORLEVEL 1 GOTO WRONG

SET PROGRAM=LCL962A
CALL MZ390 %CICSPATH%\%PROGRAM% SYSMAC(%CICSPATH%+MAC) SYSCPY(%CICSPATH%+MAC)
IF ERRORLEVEL 1 GOTO WRONG
SET PRNFILE=%CICSPATH%\%PROGRAM%.PRN
SET URFFILE=%CICSPATH%\%PROGRAM%.URF
CALL EZ390 %PROGPATH%\UNREF ASCII
IF ERRORLEVEL 1 GOTO WRONG

SET PROGRAM=CEMTIENQ
CALL MZ390 %CICSPATH%\%PROGRAM% SYSMAC(%CICSPATH%+MAC) SYSCPY(%CICSPATH%+MAC)
IF ERRORLEVEL 1 GOTO WRONG
CALL LZ390 %CICSPATH%\%PROGRAM%
IF ERRORLEVEL 1 GOTO WRONG
SET PRNFILE=%CICSPATH%\%PROGRAM%.PRN
SET URFFILE=%CICSPATH%\%PROGRAM%.URF
CALL EZ390 %PROGPATH%\UNREF ASCII
IF ERRORLEVEL 1 GOTO WRONG

SET PROGRAM=CEMTISYS
CALL MZ390 %CICSPATH%\%PROGRAM% SYSMAC(%CICSPATH%+MAC) SYSCPY(%CICSPATH%+MAC)
IF ERRORLEVEL 1 GOTO WRONG
CALL LZ390 %CICSPATH%\%PROGRAM%
IF ERRORLEVEL 1 GOTO WRONG
SET PRNFILE=%CICSPATH%\%PROGRAM%.PRN
SET URFFILE=%CICSPATH%\%PROGRAM%.URF
CALL EZ390 %PROGPATH%\UNREF ASCII
IF ERRORLEVEL 1 GOTO WRONG

SET PROGRAM=CEMTITER
CALL MZ390 %CICSPATH%\%PROGRAM% SYSMAC(%CICSPATH%+MAC) SYSCPY(%CICSPATH%+MAC)
IF ERRORLEVEL 1 GOTO WRONG
CALL LZ390 %CICSPATH%\%PROGRAM%
IF ERRORLEVEL 1 GOTO WRONG
SET PRNFILE=%CICSPATH%\%PROGRAM%.PRN
SET URFFILE=%CICSPATH%\%PROGRAM%.URF
CALL EZ390 %PROGPATH%\UNREF ASCII
IF ERRORLEVEL 1 GOTO WRONG

SET PROGRAM=CEMTITRN
CALL MZ390 %CICSPATH%\%PROGRAM% SYSMAC(%CICSPATH%+MAC) SYSCPY(%CICSPATH%+MAC)
IF ERRORLEVEL 1 GOTO WRONG
CALL LZ390 %CICSPATH%\%PROGRAM%
IF ERRORLEVEL 1 GOTO WRONG
SET PRNFILE=%CICSPATH%\%PROGRAM%.PRN
SET URFFILE=%CICSPATH%\%PROGRAM%.URF
CALL EZ390 %PROGPATH%\UNREF ASCII
IF ERRORLEVEL 1 GOTO WRONG

SET PROGRAM=CEMTFILE
CALL MZ390 %CICSPATH%\%PROGRAM% SYSMAC(%CICSPATH%+MAC) SYSCPY(%CICSPATH%+MAC)
IF ERRORLEVEL 1 GOTO WRONG
CALL LZ390 %CICSPATH%\%PROGRAM%
IF ERRORLEVEL 1 GOTO WRONG
SET PRNFILE=%CICSPATH%\%PROGRAM%.PRN
SET URFFILE=%CICSPATH%\%PROGRAM%.URF
CALL EZ390 %PROGPATH%\UNREF ASCII
IF ERRORLEVEL 1 GOTO WRONG
rem
rem TABLES
rem
SET PROGRAM=DFHPCT
CALL MZ390 %CICSPATH%\%PROGRAM% SYSMAC(%CICSPATH%+MAC) SYSCPY(%CICSPATH%+MAC)
IF ERRORLEVEL 1 GOTO WRONG
CALL LZ390 %CICSPATH%\%PROGRAM%
IF ERRORLEVEL 1 GOTO WRONG

SET PROGRAM=DFHFCT
CALL MZ390 %CICSPATH%\%PROGRAM% SYSMAC(%CICSPATH%+MAC) SYSCPY(%CICSPATH%+MAC)
IF ERRORLEVEL 1 GOTO WRONG
CALL LZ390 %CICSPATH%\%PROGRAM%
IF ERRORLEVEL 1 GOTO WRONG
rem
rem MAPS
rem
SET PROGRAM=MAPLOGO
CALL MZ390 %CICSPATH%\%PROGRAM% SYSMAC(%CICSPATH%+MAC) SYSCPY(MAC) SYSPARM(MAP)
IF ERRORLEVEL 1 GOTO WRONG
CALL LZ390 %CICSPATH%\%PROGRAM%
IF ERRORLEVEL 1 GOTO WRONG
SET PRNFILE=%CICSPATH%\%PROGRAM%.PRN
SET URFFILE=%CICSPATH%\%PROGRAM%.URF
CALL EZ390 %PROGPATH%\UNREF ASCII
IF ERRORLEVEL 1 GOTO WRONG

SET PROGRAM=MAP01
CALL MZ390 %CICSPATH%\%PROGRAM% SYSMAC(%CICSPATH%+MAC) SYSCPY(MAC) SYSPARM(DSECT) SYSPRN(%CICSPATH%\%PROGRAM%.PR1)
IF ERRORLEVEL 1 GOTO WRONG
CALL MZ390 %CICSPATH%\%PROGRAM% SYSMAC(%CICSPATH%+MAC) SYSCPY(MAC) SYSPARM(MAP)
IF ERRORLEVEL 1 GOTO WRONG
CALL LZ390 %CICSPATH%\%PROGRAM%
IF ERRORLEVEL 1 GOTO WRONG
SET PRNFILE=%CICSPATH%\%PROGRAM%.PRN
SET URFFILE=%CICSPATH%\%PROGRAM%.URF
CALL EZ390 %PROGPATH%\UNREF ASCII
IF ERRORLEVEL 1 GOTO WRONG

SET PROGRAM=MAP02
CALL MZ390 %CICSPATH%\%PROGRAM% SYSMAC(%CICSPATH%+MAC) SYSCPY(MAC) SYSPARM(DSECT) SYSPRN(%CICSPATH%\%PROGRAM%.PR1)
IF ERRORLEVEL 1 GOTO WRONG
CALL MZ390 %CICSPATH%\%PROGRAM% SYSMAC(%CICSPATH%+MAC) SYSCPY(MAC) SYSPARM(MAP)
IF ERRORLEVEL 1 GOTO WRONG
CALL LZ390 %CICSPATH%\%PROGRAM%
IF ERRORLEVEL 1 GOTO WRONG
SET PRNFILE=%CICSPATH%\%PROGRAM%.PRN
SET URFFILE=%CICSPATH%\%PROGRAM%.URF
CALL EZ390 %PROGPATH%\UNREF ASCII
IF ERRORLEVEL 1 GOTO WRONG

SET PROGRAM=MAP01C
CALL MZ390 %CICSPATH%\%PROGRAM% SYSMAC(%CICSPATH%+MAC) SYSCPY(MAC) SYSPARM(DSECT) SYSPRN(%CICSPATH%\%PROGRAM%.PR1)
IF ERRORLEVEL 1 GOTO WRONG
CALL MZ390 %CICSPATH%\%PROGRAM% SYSMAC(%CICSPATH%+MAC) SYSCPY(MAC) SYSPARM(MAP)
IF ERRORLEVEL 1 GOTO WRONG
CALL LZ390 %CICSPATH%\%PROGRAM%
IF ERRORLEVEL 1 GOTO WRONG
SET PRNFILE=%CICSPATH%\%PROGRAM%.PRN
SET URFFILE=%CICSPATH%\%PROGRAM%.URF
CALL EZ390 %PROGPATH%\UNREF ASCII
IF ERRORLEVEL 1 GOTO WRONG

SET PROGRAM=MAPCEMT
CALL MZ390 %CICSPATH%\%PROGRAM% SYSMAC(%CICSPATH%+MAC) SYSCPY(MAC) SYSPARM(DSECT) SYSPRN(%CICSPATH%\%PROGRAM%.PR1)
IF ERRORLEVEL 1 GOTO WRONG
CALL MZ390 %CICSPATH%\%PROGRAM% SYSMAC(%CICSPATH%+MAC) SYSCPY(MAC) SYSPARM(MAP)
IF ERRORLEVEL 1 GOTO WRONG
CALL LZ390 %CICSPATH%\%PROGRAM%
IF ERRORLEVEL 1 GOTO WRONG
SET PRNFILE=%CICSPATH%\%PROGRAM%.PRN
SET URFFILE=%CICSPATH%\%PROGRAM%.URF
CALL EZ390 %PROGPATH%\UNREF ASCII
IF ERRORLEVEL 1 GOTO WRONG

SET PROGRAM=MAPEDF
CALL MZ390 %CICSPATH%\%PROGRAM% SYSMAC(%CICSPATH%+MAC) SYSCPY(MAC) SYSPARM(DSECT) SYSPRN(%CICSPATH%\%PROGRAM%.PR1) NOTIME
IF ERRORLEVEL 1 GOTO WRONG
CALL MZ390 %CICSPATH%\%PROGRAM% SYSMAC(%CICSPATH%+MAC) SYSCPY(MAC) SYSPARM(MAP) NOTIME
IF ERRORLEVEL 1 GOTO WRONG
CALL LZ390 %CICSPATH%\%PROGRAM%
IF ERRORLEVEL 1 GOTO WRONG
SET PRNFILE=%CICSPATH%\%PROGRAM%.PRN
SET URFFILE=%CICSPATH%\%PROGRAM%.URF
CALL EZ390 %PROGPATH%\UNREF ASCII NOTIME
IF ERRORLEVEL 1 GOTO WRONG

SET PROGRAM=LCLCEDF
CALL MZ390 %CICSPATH%\%PROGRAM% NOEDF SYSMAC(%CICSPATH%+MAC) SYSCPY(%CICSPATH%+MAC)
IF ERRORLEVEL 1 GOTO WRONG
CALL LZ390 %CICSPATH%\%PROGRAM%
IF ERRORLEVEL 1 GOTO WRONG
SET PRNFILE=%CICSPATH%\%PROGRAM%.PRN
SET URFFILE=%CICSPATH%\%PROGRAM%.URF
CALL EZ390 %PROGPATH%\UNREF ASCII NOTIME
IF ERRORLEVEL 1 GOTO WRONG

rem
rem ASM PROGRAMS
rem
SET PROGRAM=MMMMCIC2
CALL MZ390 %CICSPATH%\%PROGRAM% CICS SYSMAC(%CICSPATH%+MAC) SYSCPY(%CICSPATH%+MAC)
IF ERRORLEVEL 1 GOTO WRONG
CALL LZ390 %CICSPATH%\%PROGRAM%
IF ERRORLEVEL 1 GOTO WRONG
SET PRNFILE=%CICSPATH%\%PROGRAM%.PRN
SET URFFILE=%CICSPATH%\%PROGRAM%.URF
CALL EZ390 %PROGPATH%\UNREF ASCII
IF ERRORLEVEL 1 GOTO WRONG

SET PROGRAM=TESTASGN
CALL MZ390 %CICSPATH%\%PROGRAM% CICS NOPROLOG SYSMAC(%CICSPATH%+MAC) SYSCPY(%CICSPATH%+MAC)
IF ERRORLEVEL 1 GOTO WRONG
CALL LZ390 %CICSPATH%\%PROGRAM%
IF ERRORLEVEL 1 GOTO WRONG
SET PRNFILE=%CICSPATH%\%PROGRAM%.PRN
SET URFFILE=%CICSPATH%\%PROGRAM%.URF
CALL EZ390 %PROGPATH%\UNREF ASCII
IF ERRORLEVEL 1 GOTO WRONG

SET PROGRAM=TESTBED1
CALL MZ390 %CICSPATH%\%PROGRAM% CICS NOPROLOG SYSMAC(%CICSPATH%+MAC) SYSCPY(%CICSPATH%+MAC)
IF ERRORLEVEL 1 GOTO WRONG
CALL LZ390 %CICSPATH%\%PROGRAM%
IF ERRORLEVEL 1 GOTO WRONG
SET PRNFILE=%CICSPATH%\%PROGRAM%.PRN
SET URFFILE=%CICSPATH%\%PROGRAM%.URF
CALL EZ390 %PROGPATH%\UNREF ASCII
IF ERRORLEVEL 1 GOTO WRONG

SET PROGRAM=TESTBED2
CALL MZ390 %CICSPATH%\%PROGRAM% CICS SYSMAC(%CICSPATH%+MAC) SYSCPY(%CICSPATH%+MAC)
IF ERRORLEVEL 1 GOTO WRONG
CALL LZ390 %CICSPATH%\%PROGRAM%
IF ERRORLEVEL 1 GOTO WRONG
SET PRNFILE=%CICSPATH%\%PROGRAM%.PRN
SET URFFILE=%CICSPATH%\%PROGRAM%.URF
CALL EZ390 %PROGPATH%\UNREF ASCII
IF ERRORLEVEL 1 GOTO WRONG

SET PROGRAM=TESTBED3
CALL MZ390 %CICSPATH%\%PROGRAM% CICS SYSMAC(%CICSPATH%+MAC) SYSCPY(%CICSPATH%+MAC)
IF ERRORLEVEL 1 GOTO WRONG
CALL LZ390 %CICSPATH%\%PROGRAM%
IF ERRORLEVEL 1 GOTO WRONG
SET PRNFILE=%CICSPATH%\%PROGRAM%.PRN
SET URFFILE=%CICSPATH%\%PROGRAM%.URF
CALL EZ390 %PROGPATH%\UNREF ASCII
IF ERRORLEVEL 1 GOTO WRONG

SET PROGRAM=TESTBED4
CALL MZ390 %CICSPATH%\%PROGRAM% CICS SYSMAC(%CICSPATH%+MAC) SYSCPY(%CICSPATH%+MAC)
IF ERRORLEVEL 1 GOTO WRONG
CALL LZ390 %CICSPATH%\%PROGRAM%
IF ERRORLEVEL 1 GOTO WRONG
SET PRNFILE=%CICSPATH%\%PROGRAM%.PRN
SET URFFILE=%CICSPATH%\%PROGRAM%.URF
CALL EZ390 %PROGPATH%\UNREF ASCII
IF ERRORLEVEL 1 GOTO WRONG

SET PROGRAM=TESTBED5
CALL MZ390 %CICSPATH%\%PROGRAM% CICS NOPROLOG SYSMAC(%CICSPATH%+MAC) SYSCPY(%CICSPATH%+MAC)
IF ERRORLEVEL 1 GOTO WRONG
CALL LZ390 %CICSPATH%\%PROGRAM%
IF ERRORLEVEL 1 GOTO WRONG
SET PRNFILE=%CICSPATH%\%PROGRAM%.PRN
SET URFFILE=%CICSPATH%\%PROGRAM%.URF
CALL EZ390 %PROGPATH%\UNREF ASCII
IF ERRORLEVEL 1 GOTO WRONG

SET PROGRAM=TESTBED6
CALL MZ390 %CICSPATH%\%PROGRAM% CICS NOPROLOG SYSMAC(%CICSPATH%+MAC) SYSCPY(%CICSPATH%+MAC)
IF ERRORLEVEL 1 GOTO WRONG
CALL LZ390 %CICSPATH%\%PROGRAM%
IF ERRORLEVEL 1 GOTO WRONG
SET PRNFILE=%CICSPATH%\%PROGRAM%.PRN
SET URFFILE=%CICSPATH%\%PROGRAM%.URF
CALL EZ390 %PROGPATH%\UNREF ASCII
IF ERRORLEVEL 1 GOTO WRONG

SET PROGRAM=TESTBED7
CALL MZ390 %CICSPATH%\%PROGRAM% CICS SYSMAC(%CICSPATH%+MAC) SYSCPY(%CICSPATH%+MAC)
IF ERRORLEVEL 1 GOTO WRONG
CALL LZ390 %CICSPATH%\%PROGRAM%
IF ERRORLEVEL 1 GOTO WRONG
SET PRNFILE=%CICSPATH%\%PROGRAM%.PRN
SET URFFILE=%CICSPATH%\%PROGRAM%.URF
CALL EZ390 %PROGPATH%\UNREF ASCII
IF ERRORLEVEL 1 GOTO WRONG

SET PROGRAM=TESTBED8
CALL MZ390 %CICSPATH%\%PROGRAM% CICS SYSMAC(%CICSPATH%+MAC) SYSCPY(%CICSPATH%+MAC)
IF ERRORLEVEL 1 GOTO WRONG
CALL LZ390 %CICSPATH%\%PROGRAM%
IF ERRORLEVEL 1 GOTO WRONG
SET PRNFILE=%CICSPATH%\%PROGRAM%.PRN
SET URFFILE=%CICSPATH%\%PROGRAM%.URF
CALL EZ390 %PROGPATH%\UNREF ASCII
IF ERRORLEVEL 1 GOTO WRONG

SET PROGRAM=TESTBED9
CALL MZ390 %CICSPATH%\%PROGRAM% CICS NOPROLOG SYSMAC(%CICSPATH%+MAC) SYSCPY(%CICSPATH%+MAC)
IF ERRORLEVEL 1 GOTO WRONG
CALL LZ390 %CICSPATH%\%PROGRAM%
IF ERRORLEVEL 1 GOTO WRONG
SET PRNFILE=%CICSPATH%\%PROGRAM%.PRN
SET URFFILE=%CICSPATH%\%PROGRAM%.URF
CALL EZ390 %PROGPATH%\UNREF ASCII
IF ERRORLEVEL 1 GOTO WRONG

SET PROGRAM=TESTBMS1
CALL MZ390 %CICSPATH%\%PROGRAM% CICS NOPROLOG SYSMAC(%CICSPATH%+MAC) SYSCPY(%CICSPATH%+MAC)
IF ERRORLEVEL 1 GOTO WRONG
CALL LZ390 %CICSPATH%\%PROGRAM%
IF ERRORLEVEL 1 GOTO WRONG
SET PRNFILE=%CICSPATH%\%PROGRAM%.PRN
SET URFFILE=%CICSPATH%\%PROGRAM%.URF
CALL EZ390 %PROGPATH%\UNREF ASCII
IF ERRORLEVEL 1 GOTO WRONG

SET PROGRAM=TESTBMS2
CALL MZ390 %CICSPATH%\%PROGRAM% CICS SYSMAC(%CICSPATH%+MAC) SYSCPY(%CICSPATH%+MAC)
IF ERRORLEVEL 1 GOTO WRONG
CALL LZ390 %CICSPATH%\%PROGRAM%
IF ERRORLEVEL 1 GOTO WRONG
SET PRNFILE=%CICSPATH%\%PROGRAM%.PRN
SET URFFILE=%CICSPATH%\%PROGRAM%.URF
CALL EZ390 %PROGPATH%\UNREF ASCII
IF ERRORLEVEL 1 GOTO WRONG

SET PROGRAM=TESTCHN1
CALL MZ390 %CICSPATH%\%PROGRAM% CICS NOPROLOG SYSMAC(%CICSPATH%+MAC) SYSCPY(%CICSPATH%+MAC)
IF ERRORLEVEL 1 GOTO WRONG
CALL LZ390 %CICSPATH%\%PROGRAM%
IF ERRORLEVEL 1 GOTO WRONG
SET PRNFILE=%CICSPATH%\%PROGRAM%.PRN
SET URFFILE=%CICSPATH%\%PROGRAM%.URF
CALL EZ390 %PROGPATH%\UNREF ASCII
IF ERRORLEVEL 1 GOTO WRONG

SET PROGRAM=TESTCHN2
CALL MZ390 %CICSPATH%\%PROGRAM% CICS NOPROLOG SYSMAC(%CICSPATH%+MAC) SYSCPY(%CICSPATH%+MAC)
IF ERRORLEVEL 1 GOTO WRONG
CALL LZ390 %CICSPATH%\%PROGRAM%
IF ERRORLEVEL 1 GOTO WRONG
SET PRNFILE=%CICSPATH%\%PROGRAM%.PRN
SET URFFILE=%CICSPATH%\%PROGRAM%.URF
CALL EZ390 %PROGPATH%\UNREF ASCII
IF ERRORLEVEL 1 GOTO WRONG

SET PROGRAM=TESTVSM1
CALL MZ390 %CICSPATH%\%PROGRAM% CICS NOPROLOG SYSMAC(%CICSPATH%+MAC) SYSCPY(%CICSPATH%+MAC)
IF ERRORLEVEL 1 GOTO WRONG
CALL LZ390 %CICSPATH%\%PROGRAM%
IF ERRORLEVEL 1 GOTO WRONG
SET PRNFILE=%CICSPATH%\%PROGRAM%.PRN
SET URFFILE=%CICSPATH%\%PROGRAM%.URF
CALL EZ390 %PROGPATH%\UNREF ASCII
IF ERRORLEVEL 1 GOTO WRONG

SET PROGRAM=TESTVSM2
CALL MZ390 %CICSPATH%\%PROGRAM% CICS NOPROLOG SYSMAC(%CICSPATH%+MAC) SYSCPY(%CICSPATH%+MAC)
IF ERRORLEVEL 1 GOTO WRONG
CALL LZ390 %CICSPATH%\%PROGRAM%
IF ERRORLEVEL 1 GOTO WRONG
SET PRNFILE=%CICSPATH%\%PROGRAM%.PRN
SET URFFILE=%CICSPATH%\%PROGRAM%.URF
CALL EZ390 %PROGPATH%\UNREF ASCII
IF ERRORLEVEL 1 GOTO WRONG

SET PROGRAM=TESTVSM3
CALL MZ390 %CICSPATH%\%PROGRAM% CICS NOPROLOG SYSMAC(%CICSPATH%+MAC) SYSCPY(%CICSPATH%+MAC)
IF ERRORLEVEL 1 GOTO WRONG
CALL LZ390 %CICSPATH%\%PROGRAM%
IF ERRORLEVEL 1 GOTO WRONG
SET PRNFILE=%CICSPATH%\%PROGRAM%.PRN
SET URFFILE=%CICSPATH%\%PROGRAM%.URF
CALL EZ390 %PROGPATH%\UNREF ASCII
IF ERRORLEVEL 1 GOTO WRONG

SET PROGRAM=TESTCIC1
CALL MZ390 %CICSPATH%\%PROGRAM% CICS SYSMAC(%CICSPATH%+MAC) SYSCPY(%CICSPATH%+MAC)
IF ERRORLEVEL 1 GOTO WRONG
CALL LZ390 %CICSPATH%\%PROGRAM%
IF ERRORLEVEL 1 GOTO WRONG
SET PRNFILE=%CICSPATH%\%PROGRAM%.PRN
SET URFFILE=%CICSPATH%\%PROGRAM%.URF
CALL EZ390 %PROGPATH%\UNREF ASCII
IF ERRORLEVEL 1 GOTO WRONG

SET PROGRAM=TESTCIC2
CALL MZ390 %CICSPATH%\%PROGRAM% CICS SYSMAC(%CICSPATH%+MAC) SYSCPY(%CICSPATH%+MAC)
IF ERRORLEVEL 1 GOTO WRONG
CALL LZ390 %CICSPATH%\%PROGRAM%
IF ERRORLEVEL 1 GOTO WRONG
SET PRNFILE=%CICSPATH%\%PROGRAM%.PRN
SET URFFILE=%CICSPATH%\%PROGRAM%.URF
CALL EZ390 %PROGPATH%\UNREF ASCII
IF ERRORLEVEL 1 GOTO WRONG

SET PROGRAM=TESTGUI4
CALL MZ390 %CICSPATH%\%PROGRAM% CICS SYSMAC(%CICSPATH%+MAC) SYSCPY(%CICSPATH%+MAC)
IF ERRORLEVEL 1 GOTO WRONG
CALL LZ390 %CICSPATH%\%PROGRAM%
IF ERRORLEVEL 1 GOTO WRONG
SET PRNFILE=%CICSPATH%\%PROGRAM%.PRN
SET URFFILE=%CICSPATH%\%PROGRAM%.URF
CALL EZ390 %PROGPATH%\UNREF ASCII
IF ERRORLEVEL 1 GOTO WRONG

SET PROGRAM=TESTGUI6
CALL MZ390 %CICSPATH%\%PROGRAM% CICS SYSMAC(%CICSPATH%+MAC) SYSCPY(%CICSPATH%+MAC)
IF ERRORLEVEL 1 GOTO WRONG
CALL LZ390 %CICSPATH%\%PROGRAM%
IF ERRORLEVEL 1 GOTO WRONG
SET PRNFILE=%CICSPATH%\%PROGRAM%.PRN
SET URFFILE=%CICSPATH%\%PROGRAM%.URF
CALL EZ390 %PROGPATH%\UNREF ASCII
IF ERRORLEVEL 1 GOTO WRONG

SET PROGRAM=TESTIC01
CALL MZ390 %CICSPATH%\%PROGRAM% CICS NOPROLOG SYSMAC(%CICSPATH%+MAC) SYSCPY(%CICSPATH%+MAC)
IF ERRORLEVEL 1 GOTO WRONG
CALL LZ390 %CICSPATH%\%PROGRAM%
IF ERRORLEVEL 1 GOTO WRONG
SET PRNFILE=%CICSPATH%\%PROGRAM%.PRN
SET URFFILE=%CICSPATH%\%PROGRAM%.URF
CALL EZ390 %PROGPATH%\UNREF ASCII
IF ERRORLEVEL 1 GOTO WRONG

SET PROGRAM=TESTIC02
CALL MZ390 %CICSPATH%\%PROGRAM% CICS NOPROLOG SYSMAC(%CICSPATH%+MAC) SYSCPY(%CICSPATH%+MAC)
IF ERRORLEVEL 1 GOTO WRONG
CALL LZ390 %CICSPATH%\%PROGRAM%
IF ERRORLEVEL 1 GOTO WRONG
SET PRNFILE=%CICSPATH%\%PROGRAM%.PRN
SET URFFILE=%CICSPATH%\%PROGRAM%.URF
CALL EZ390 %PROGPATH%\UNREF ASCII
IF ERRORLEVEL 1 GOTO WRONG

SET PROGRAM=TESTIC03
CALL MZ390 %CICSPATH%\%PROGRAM% CICS SYSMAC(%CICSPATH%+MAC) SYSCPY(%CICSPATH%+MAC)
IF ERRORLEVEL 1 GOTO WRONG
CALL LZ390 %CICSPATH%\%PROGRAM%
IF ERRORLEVEL 1 GOTO WRONG
SET PRNFILE=%CICSPATH%\%PROGRAM%.PRN
SET URFFILE=%CICSPATH%\%PROGRAM%.URF
CALL EZ390 %PROGPATH%\UNREF ASCII
IF ERRORLEVEL 1 GOTO WRONG

SET PROGRAM=TESTIC04
CALL MZ390 %CICSPATH%\%PROGRAM% CICS NOPROLOG SYSMAC(%CICSPATH%+MAC) SYSCPY(%CICSPATH%+MAC)
IF ERRORLEVEL 1 GOTO WRONG
CALL LZ390 %CICSPATH%\%PROGRAM%
IF ERRORLEVEL 1 GOTO WRONG
SET PRNFILE=%CICSPATH%\%PROGRAM%.PRN
SET URFFILE=%CICSPATH%\%PROGRAM%.URF
CALL EZ390 %PROGPATH%\UNREF ASCII
IF ERRORLEVEL 1 GOTO WRONG

SET PROGRAM=TESTENQ1
CALL MZ390 %CICSPATH%\%PROGRAM% CICS SYSMAC(%CICSPATH%+MAC) SYSCPY(%CICSPATH%+MAC)
IF ERRORLEVEL 1 GOTO WRONG
CALL LZ390 %CICSPATH%\%PROGRAM%
IF ERRORLEVEL 1 GOTO WRONG
SET PRNFILE=%CICSPATH%\%PROGRAM%.PRN
SET URFFILE=%CICSPATH%\%PROGRAM%.URF
CALL EZ390 %PROGPATH%\UNREF ASCII
IF ERRORLEVEL 1 GOTO WRONG

SET PROGRAM=TESTNT01
CALL MZ390 %CICSPATH%\%PROGRAM% CICS NOPROLOG SYSMAC(%CICSPATH%+MAC) SYSCPY(%CICSPATH%+MAC)
IF ERRORLEVEL 1 GOTO WRONG
CALL LZ390 %CICSPATH%\%PROGRAM%
IF ERRORLEVEL 1 GOTO WRONG
SET PRNFILE=%CICSPATH%\%PROGRAM%.PRN
SET URFFILE=%CICSPATH%\%PROGRAM%.URF
CALL EZ390 %PROGPATH%\UNREF ASCII
IF ERRORLEVEL 1 GOTO WRONG

SET PROGRAM=TESTNT02
CALL MZ390 %CICSPATH%\%PROGRAM% CICS NOPROLOG SYSMAC(%CICSPATH%+MAC) SYSCPY(%CICSPATH%+MAC)
IF ERRORLEVEL 1 GOTO WRONG
CALL LZ390 %CICSPATH%\%PROGRAM%
IF ERRORLEVEL 1 GOTO WRONG
SET PRNFILE=%CICSPATH%\%PROGRAM%.PRN
SET URFFILE=%CICSPATH%\%PROGRAM%.URF
CALL EZ390 %PROGPATH%\UNREF ASCII
IF ERRORLEVEL 1 GOTO WRONG

SET PROGRAM=TESTSETF
CALL MZ390 %CICSPATH%\%PROGRAM% CICS NOPROLOG SYSMAC(%CICSPATH%+MAC) SYSCPY(%CICSPATH%+MAC)
IF ERRORLEVEL 1 GOTO WRONG
CALL LZ390 %CICSPATH%\%PROGRAM%
IF ERRORLEVEL 1 GOTO WRONG
SET PRNFILE=%CICSPATH%\%PROGRAM%.PRN
SET URFFILE=%CICSPATH%\%PROGRAM%.URF
CALL EZ390 %PROGPATH%\UNREF ASCII
IF ERRORLEVEL 1 GOTO WRONG

SET PROGRAM=Z390CEBR
CALL MZ390 %CICSPATH%\%PROGRAM% CICS NOPROLOG SYSMAC(%CICSPATH%+MAC) SYSCPY(%CICSPATH%+MAC+.)
IF ERRORLEVEL 1 GOTO WRONG
CALL LZ390 %CICSPATH%\%PROGRAM%
IF ERRORLEVEL 1 GOTO WRONG
SET PRNFILE=%CICSPATH%\%PROGRAM%.PRN
SET URFFILE=%CICSPATH%\%PROGRAM%.URF
CALL EZ390 %PROGPATH%\UNREF ASCII
IF ERRORLEVEL 1 GOTO WRONG

SET PROGRAM=Z390CEDF
CALL MZ390 %CICSPATH%\%PROGRAM% CICS NOPROLOG NOEDF SYSMAC(%CICSPATH%+MAC) SYSCPY(%CICSPATH%+MAC+.) NOTIME
IF ERRORLEVEL 1 GOTO WRONG
CALL LZ390 %CICSPATH%\%PROGRAM%
IF ERRORLEVEL 1 GOTO WRONG
SET PRNFILE=%CICSPATH%\%PROGRAM%.PRN
SET URFFILE=%CICSPATH%\%PROGRAM%.URF
CALL EZ390 %PROGPATH%\UNREF ASCII NOTIME
IF ERRORLEVEL 1 GOTO WRONG

SET PROGRAM=Z390CEMT
CALL MZ390 %CICSPATH%\%PROGRAM% CICS NOPROLOG SYSMAC(%CICSPATH%+MAC) SYSCPY(%CICSPATH%+MAC+.)
IF ERRORLEVEL 1 GOTO WRONG
CALL LZ390 %CICSPATH%\%PROGRAM%
IF ERRORLEVEL 1 GOTO WRONG
SET PRNFILE=%CICSPATH%\%PROGRAM%.PRN
SET URFFILE=%CICSPATH%\%PROGRAM%.URF
CALL EZ390 %PROGPATH%\UNREF ASCII
IF ERRORLEVEL 1 GOTO WRONG

SET PROGRAM=Z390CICS
CALL MZ390 %CICSPATH%\%PROGRAM% SYSMAC(%CICSPATH%+MAC+.) SYSCPY(%CICSPATH%+MAC+.)
IF ERRORLEVEL 1 GOTO WRONG
CALL LZ390 %CICSPATH%\%PROGRAM%
IF ERRORLEVEL 1 GOTO WRONG
SET PRNFILE=%CICSPATH%\%PROGRAM%.PRN
SET URFFILE=%CICSPATH%\%PROGRAM%.URF
CALL EZ390 %PROGPATH%\UNREF ASCII
IF ERRORLEVEL 1 GOTO WRONG

SET PROGRAM=Z390COMP
CALL MZ390 %CICSPATH%\%PROGRAM% SYSMAC(%CICSPATH%+MAC+.) SYSCPY(%CICSPATH%+MAC+.) ASCII
IF ERRORLEVEL 1 GOTO WRONG
CALL LZ390 %CICSPATH%\%PROGRAM%
IF ERRORLEVEL 1 GOTO WRONG
SET PRNFILE=%CICSPATH%\%PROGRAM%.PRN
SET URFFILE=%CICSPATH%\%PROGRAM%.URF
CALL EZ390 %PROGPATH%\UNREF ASCII
IF ERRORLEVEL 1 GOTO WRONG

SET PROGRAM=Z390KCP
CALL MZ390 %CICSPATH%\%PROGRAM% GUAM NOEDF SYSMAC(%CICSPATH%+MAC) SYSCPY(%CICSPATH%+MAC+.)
IF ERRORLEVEL 1 GOTO WRONG
CALL LZ390 %CICSPATH%\%PROGRAM%
IF ERRORLEVEL 1 GOTO WRONG
SET PRNFILE=%CICSPATH%\%PROGRAM%.PRN
SET URFFILE=%CICSPATH%\%PROGRAM%.URF
CALL EZ390 %PROGPATH%\UNREF ASCII
IF ERRORLEVEL 1 GOTO WRONG

SET PROGRAM=Z390LCL
CALL MZ390 %CICSPATH%\%PROGRAM% GUAM SYSMAC(%CICSPATH%+MAC) SYSCPY(%CICSPATH%+MAC+.)
IF ERRORLEVEL 1 GOTO WRONG
CALL LZ390 %CICSPATH%\%PROGRAM%
IF ERRORLEVEL 1 GOTO WRONG
SET PRNFILE=%CICSPATH%\%PROGRAM%.PRN
SET URFFILE=%CICSPATH%\%PROGRAM%.URF
CALL EZ390 %PROGPATH%\UNREF ASCII
IF ERRORLEVEL 1 GOTO WRONG

SET PROGRAM=Z390LOGO
CALL MZ390 %CICSPATH%\%PROGRAM% CICS SYSMAC(%CICSPATH%+MAC) SYSCPY(%CICSPATH%+MAC+.)
IF ERRORLEVEL 1 GOTO WRONG
CALL LZ390 %CICSPATH%\%PROGRAM%
IF ERRORLEVEL 1 GOTO WRONG
SET PRNFILE=%CICSPATH%\%PROGRAM%.PRN
SET URFFILE=%CICSPATH%\%PROGRAM%.URF
CALL EZ390 %PROGPATH%\UNREF ASCII
IF ERRORLEVEL 1 GOTO WRONG

SET PROGRAM=Z390RMTE
CALL MZ390 %CICSPATH%\%PROGRAM% ASCII SYSMAC(MAC) SYSCPY(MAC)
IF ERRORLEVEL 1 GOTO WRONG
CALL LZ390 %CICSPATH%\%PROGRAM%
IF ERRORLEVEL 1 GOTO WRONG
SET PRNFILE=%CICSPATH%\%PROGRAM%.PRN
SET URFFILE=%CICSPATH%\%PROGRAM%.URF
CALL EZ390 %PROGPATH%\UNREF ASCII
IF ERRORLEVEL 1 GOTO WRONG

SET PROGRAM=Z390SEQ
CALL MZ390 %CICSPATH%\%PROGRAM% SYSMAC(%CICSPATH%+MAC+.) SYSCPY(MAC+.) ASCII
IF ERRORLEVEL 1 GOTO WRONG
CALL LZ390 %CICSPATH%\%PROGRAM%
IF ERRORLEVEL 1 GOTO WRONG
SET PRNFILE=%CICSPATH%\%PROGRAM%.PRN
SET URFFILE=%CICSPATH%\%PROGRAM%.URF
CALL EZ390 %PROGPATH%\UNREF ASCII
IF ERRORLEVEL 1 GOTO WRONG
rem
rem COBOL PROGRAMS
rem
SET PROGRAM=TESTBEC1
CALL ZC390CL %CICSPATH%\%PROGRAM% CICS SYSMAC(%CICSPATH%+ZCOBOL+%ZC39PATH%+CICS+MAC) SYSCPY(%CICSPATH%+ZCOBOL+%ZC39PATH%+MAC+.)
IF ERRORLEVEL 1 GOTO WRONG
SET PRNFILE=%CICSPATH%\%PROGRAM%.PRN
SET URFFILE=%CICSPATH%\%PROGRAM%.URF
CALL EZ390 %PROGPATH%\UNREF ASCII %1 %2
IF ERRORLEVEL 1 GOTO WRONG

SET PROGRAM=TESTBEC2
CALL ZC390CL %CICSPATH%\%PROGRAM% CICS SYSMAC(%CICSPATH%+ZCOBOL+%ZC39PATH%+CICS+MAC) SYSCPY(%CICSPATH%+ZCOBOL+%ZC39PATH%+MAC+.)
IF ERRORLEVEL 1 GOTO WRONG
SET PRNFILE=%CICSPATH%\%PROGRAM%.PRN
SET URFFILE=%CICSPATH%\%PROGRAM%.URF
CALL EZ390 %PROGPATH%\UNREF ASCII %1 %2
IF ERRORLEVEL 1 GOTO WRONG

SET PROGRAM=TESTBEC4
CALL ZC390CL %CICSPATH%\%PROGRAM% CICS SYSMAC(%CICSPATH%+ZCOBOL+%ZC39PATH%+CICS+MAC) SYSCPY(%CICSPATH%+ZCOBOL+%ZC39PATH%+MAC+.)
IF ERRORLEVEL 1 GOTO WRONG
SET PRNFILE=%CICSPATH%\%PROGRAM%.PRN
SET URFFILE=%CICSPATH%\%PROGRAM%.URF
CALL EZ390 %PROGPATH%\UNREF ASCII %1 %2
IF ERRORLEVEL 1 GOTO WRONG

SET PROGRAM=TESTBEC5
CALL ZC390CL %CICSPATH%\%PROGRAM% CICS SYSMAC(%CICSPATH%+ZCOBOL+%ZC39PATH%+CICS+MAC) SYSCPY(%CICSPATH%+ZCOBOL+%ZC39PATH%+MAC+.)
IF ERRORLEVEL 1 GOTO WRONG
SET PRNFILE=%CICSPATH%\%PROGRAM%.PRN
SET URFFILE=%CICSPATH%\%PROGRAM%.URF
CALL EZ390 %PROGPATH%\UNREF ASCII %1 %2
IF ERRORLEVEL 1 GOTO WRONG

SET PROGRAM=TESTBEC6
CALL ZC390CL %CICSPATH%\%PROGRAM% CICS SYSMAC(%CICSPATH%+ZCOBOL+%ZC39PATH%+CICS+MAC) SYSCPY(%CICSPATH%+ZCOBOL+%ZC39PATH%+MAC+.)
IF ERRORLEVEL 1 GOTO WRONG
SET PRNFILE=%CICSPATH%\%PROGRAM%.PRN
SET URFFILE=%CICSPATH%\%PROGRAM%.URF
CALL EZ390 %PROGPATH%\UNREF ASCII %1 %2
IF ERRORLEVEL 1 GOTO WRONG

SET PROGRAM=TESTBEC7
CALL ZC390CL %CICSPATH%\%PROGRAM% CICS SYSMAC(%CICSPATH%+ZCOBOL+%ZC39PATH%+CICS+MAC) SYSCPY(%CICSPATH%+ZCOBOL+%ZC39PATH%+MAC+.)
IF ERRORLEVEL 1 GOTO WRONG
SET PRNFILE=%CICSPATH%\%PROGRAM%.PRN
SET URFFILE=%CICSPATH%\%PROGRAM%.URF
CALL EZ390 %PROGPATH%\UNREF ASCII %1 %2
IF ERRORLEVEL 1 GOTO WRONG

SET PROGRAM=TESTBEC8
CALL ZC390CL %CICSPATH%\%PROGRAM% CICS SYSMAC(%CICSPATH%+ZCOBOL+%ZC39PATH%+CICS+MAC) SYSCPY(%CICSPATH%+ZCOBOL+%ZC39PATH%+MAC+.)
IF ERRORLEVEL 1 GOTO WRONG
SET PRNFILE=%CICSPATH%\%PROGRAM%.PRN
SET URFFILE=%CICSPATH%\%PROGRAM%.URF
CALL EZ390 %PROGPATH%\UNREF ASCII %1 %2
IF ERRORLEVEL 1 GOTO WRONG

SET PROGRAM=TESTBEC9
CALL ZC390CL %CICSPATH%\%PROGRAM% CICS SYSMAC(%CICSPATH%+ZCOBOL+%ZC39PATH%+CICS+MAC) SYSCPY(%CICSPATH%+ZCOBOL+%ZC39PATH%+MAC+.)
IF ERRORLEVEL 1 GOTO WRONG
SET PRNFILE=%CICSPATH%\%PROGRAM%.PRN
SET URFFILE=%CICSPATH%\%PROGRAM%.URF
CALL EZ390 %PROGPATH%\UNREF ASCII %1 %2
IF ERRORLEVEL 1 GOTO WRONG

SET PROGRAM=TESTBMC1
CALL ZC390CL %CICSPATH%\%PROGRAM% CICS SYSMAC(%CICSPATH%+ZCOBOL+%ZC39PATH%+CICS+MAC) SYSCPY(%CICSPATH%+ZCOBOL+%ZC39PATH%+MAC+.)
IF ERRORLEVEL 1 GOTO WRONG
SET PRNFILE=%CICSPATH%\%PROGRAM%.PRN
SET URFFILE=%CICSPATH%\%PROGRAM%.URF
CALL EZ390 %PROGPATH%\UNREF ASCII %1 %2
IF ERRORLEVEL 1 GOTO WRONG

SET PROGRAM=TESTICC1
CALL ZC390CL %CICSPATH%\%PROGRAM% CICS SYSMAC(%CICSPATH%+ZCOBOL+%ZC39PATH%+CICS+MAC) SYSCPY(%CICSPATH%+ZCOBOL+%ZC39PATH%+MAC+.)
IF ERRORLEVEL 1 GOTO WRONG
SET PRNFILE=%CICSPATH%\%PROGRAM%.PRN
SET URFFILE=%CICSPATH%\%PROGRAM%.URF
CALL EZ390 %PROGPATH%\UNREF ASCII %1 %2
IF ERRORLEVEL 1 GOTO WRONG

SET PROGRAM=TESTVSC1
CALL ZC390CL %CICSPATH%\%PROGRAM% CICS SYSMAC(%CICSPATH%+ZCOBOL+%ZC39PATH%+CICS+MAC) SYSCPY(%CICSPATH%+ZCOBOL+%ZC39PATH%+MAC+.)
IF ERRORLEVEL 1 GOTO WRONG
SET PRNFILE=%CICSPATH%\%PROGRAM%.PRN
SET URFFILE=%CICSPATH%\%PROGRAM%.URF
CALL EZ390 %PROGPATH%\UNREF ASCII %1 %2
IF ERRORLEVEL 1 GOTO WRONG

SET PROGRAM=TESTVSC2
CALL ZC390CL %CICSPATH%\%PROGRAM% CICS SYSMAC(%CICSPATH%+ZCOBOL+%ZC39PATH%+CICS+MAC) SYSCPY(%CICSPATH%+ZCOBOL+%ZC39PATH%+MAC+.)
IF ERRORLEVEL 1 GOTO WRONG
SET PRNFILE=%CICSPATH%\%PROGRAM%.PRN
SET URFFILE=%CICSPATH%\%PROGRAM%.URF
CALL EZ390 %PROGPATH%\UNREF ASCII %1 %2
IF ERRORLEVEL 1 GOTO WRONG

SET PROGRAM=TESTVSC3
CALL ZC390CL %CICSPATH%\%PROGRAM% CICS SYSMAC(%CICSPATH%+ZCOBOL+%ZC39PATH%+CICS+MAC) SYSCPY(%CICSPATH%+ZCOBOL+%ZC39PATH%+MAC+.)
IF ERRORLEVEL 1 GOTO WRONG
SET PRNFILE=%CICSPATH%\%PROGRAM%.PRN
SET URFFILE=%CICSPATH%\%PROGRAM%.URF
CALL EZ390 %PROGPATH%\UNREF ASCII %1 %2
IF ERRORLEVEL 1 GOTO WRONG

GOTO END
:WRONG
rem ERROR ERROR ERROR
:END
