#!/bin/bash

# esf1test: read ESDS fixed length VSAM file SEQ and random RBA/XRBA

########################################
# print error message and exit
########################################

function errmsg {
    echo ERROR: $1\; exiting
    exit 8
}

########################################
# setup
########################################

cd $(dirname $0)     # set to directory of script - z390/vsam1/test/bash
cd ../../..          # up to z390

vsampath=vsam1/test
zvsam="zvsam(1)"
trace=""
if [ "$1" = "traceall" ]; then trace=traceall; shift; fi

########################################
# code
########################################

rc=0

# run ESF1TEST to create and test ESDS with 3 80 byte records

export QFILE=${vsampath}/ESF1.TF1
export VFILE=${vsampath}/TESTCAT.ESF1
rm -f ${vsampath}/ESF1.TF1
rm -f ${vsampath}/ESF1.VES
bash/asmlg ${vsampath}/ESF1TEST $1 $2 $3 $4 $5 $zvsam $trace
rc=$?
if [ $rc -ne 0 ]; then errmsg "error in ESF1TEST"; fi

exit $rc
