#!/bin/bash

# esf1err1: test ESDS fixed length POINT error with bad XRBA

########################################
# print error message and exit
########################################

function errmsg {
    echo ERROR: $1\; exiting
    exit 8
}

########################################
# setup
########################################

cd $(dirname $0)     # set to directory of script - z390/vsam1/test/bash
cd ../../..          # up to z390

vsampath=vsam1/test
zvsam="zvsam(1)"
trace=""
if [ "$1" = "traceall" ]; then trace=traceall; shift; fi

########################################
# code
########################################

rc=0

# run ESF1ERR1 to test error on bad XRBA POINT

export VFILE=${vsampath}/TESTCAT.ESF1
bash/asmlg ${vsampath}/ESF1ERR1 $1 $2 $3 $4 $5 $zvsam $trace
rc=$?
if [ $rc -ne 0 ]; then errmsg "error in ESF1ERR1"; fi

exit $rc
