#!/bin/bash

# esf1rpq1: load/unload ESF1 using RECFM=F

########################################
# print error message and exit
########################################

function errmsg {
    echo ERROR: $1\; exiting
    exit 8
}

########################################
# setup
########################################

cd $(dirname $0)     # set to directory of script - z390/vsam1/test/bash
cd ../../..          # up to z390

pgmname=esf1rpq1
vsampath=vsam1/test
zvsam="zvsam(1)"
trace=""
if [ "$1" = "traceall" ]; then trace=traceall; shift; fi

########################################
# code
########################################

rc=0

# build ESF1.VES from ESF1.TQ1

export INFILE=${vsampath}/ESF1.TQ1[RECFM=F]
export OUTFILE=${vsampath}/TESTCAT.ESF1
bash/exec linklib/REPRO $1 $2 $3 $4 $5 $zvsam $trace
rc=$?
if [ $rc -ne 0 ]; then errmsg "error in REPRO load of ESF1"; fi

# save REPRO load stats

cp linklib/REPRO.LOG ${vsampath}/${pgmname}.RLG
if [ "$trace" = "traceall" ]; then cp linklib/REPRO.TRE ${vsampath}/${pgmname}.RLE; fi

# unload ESF1.VES to ESF1.TQ2

rm -f ${vsampath}/ESF1.TQ2
export INFILE=${vsampath}/TESTCAT.ESF1
export OUTFILE=${vsampath}/ESF1.TQ2[RECFM=F]
bash/exec linklib/REPRO $1 $2 $3 $4 $5 $zvsam $trace
rc=$?
if [ $rc -ne 0 ]; then errmsg "error in REPRO unload of ESF1"; fi

# save REPRO unload stats

cp linklib/REPRO.LOG ${vsampath}/${pgmname}.RUG
if [ "$trace" = "traceall" ]; then cp linklib/REPRO.TRE ${vsampath}/${pgmname}.RUE; fi

# compare input and output QSAM files

diff ${vsampath}/ESF1.TQ1 ${vsampath}/ESF1.TQ2 > ${vsampath}/${pgmname}.DIF
rc=$?
if [ $rc -ne 0 ]; then errmsg "ESF1.TQ1 not equal to ESF1.TQ2"; fi

exit $rc
