#!/bin/bash

# esf4rpo1: load/unload ESF4 using default EF format

########################################
# print error message and exit
########################################

function errmsg {
    echo ERROR: $1\; exiting
    exit 8
}

########################################
# setup
########################################

cd $(dirname $0)     # set to directory of script - z390/vsam1/test/bash
cd ../../..          # up to z390

pgmname=esf4rpo1
vsampath=vsam1/test
zvsam="zvsam(1)"
trace=""
if [ "$1" = "traceall" ]; then trace=traceall; shift; fi

########################################
# code
########################################

rc=0

# build ESF4.VES from ESF4.TF1

export INFILE=${vsampath}/ESF4.TF1
export OUTFILE=${vsampath}/TESTCAT.ESF4
bash/exec linklib/REPRO $1 $2 $3 $4 $5 $zvsam $trace
rc=$?
if [ $rc -ne 0 ]; then errmsg "error in REPRO load of ESF4"; fi

# save REPRO load stats

cp linklib/REPRO.LOG ${vsampath}/${pgmname}.RLG
if [ "$trace" = "traceall" ]; then cp linklib/REPRO.TRE ${vsampath}/${pgmname}.RLE; fi

# unload ESF4.VES to ESF4.TF2

rm -f ${vsampath}/ESF4.TF2
export INFILE=${vsampath}/TESTCAT.ESF4
export OUTFILE=${vsampath}/ESF4.TF2
bash/exec linklib/REPRO $1 $2 $3 $4 $5 $zvsam $trace
rc=$?
if [ $rc -ne 0 ]; then errmsg "error in REPRO unload of ESF4"; fi

# save REPRO unload stats

cp linklib/REPRO.LOG ${vsampath}/${pgmname}.RUG
if [ "$trace" = "traceall" ]; then cp linklib/REPRO.TRE ${vsampath}/${pgmname}.RUE; fi

# compare input and output QSAM files

diff ${vsampath}/ESF4.TF1 ${vsampath}/ESF4.TF2 > ${vsampath}/${pgmname}.DIF
rc=$?
if [ $rc -ne 0 ]; then errmsg "ESF4.TF1 not equal to ESF4.TF2"; fi

exit $rc
