#!/bin/bash

# esv1test: read ESDS variable length VSAM file SEQ and random RBA/XRBA

########################################
# print error message and exit
########################################

function errmsg {
    echo ERROR: $1\; exiting
    exit 8
}

########################################
# setup
########################################

cd $(dirname $0)     # set to directory of script - z390/vsam1/test/bash
cd ../../..          # up to z390

vsampath=vsam1/test
zvsam="zvsam(1)"
trace=""
if [ "$1" = "traceall" ]; then trace=traceall; shift; fi

########################################
# code
########################################

rc=0

# run ESV1TEST to create and test ESDS with 3 80 byte records

export QFILE=${vsampath}/ESV1.TQ1
export VFILE=${vsampath}/TESTCAT.ESV1
# the TQ1 and VES files are recreated by ESV1TEST; the VX0 file does not exist
rm -f ${vsampath}/ESV1.TQ1
rm -f ${vsampath}/ESV1.VES
bash/asmlg ${vsampath}/ESV1TEST $1 $2 $3 $4 $5 $zvsam $trace
rc=$?
if [ $rc -ne 0 ]; then errmsg "error in ESV1TEST"; fi

exit $rc
