#!/bin/bash

# ksf1test: read KSDS KSF1NAME by key and display records

########################################
# print error message and exit
########################################

function errmsg {
    echo ERROR: $1\; exiting
    exit 8
}

########################################
# setup
########################################

cd $(dirname $0)     # set to directory of script - z390/vsam1/test/bash
cd ../../..          # up to z390

vsampath=vsam1/test
zvsam="zvsam(1)"
trace=""
if [ "$1" = "traceall" ]; then trace=traceall; shift; fi

########################################
# code
########################################

rc=0

# run KSF1TEST to read KSDS KSF1NAME by key and display records

export VFILE=${vsampath}/TESTCAT.KSF1NAME
bash/asmlg ${vsampath}/KSF1TEST $1 $2 $3 $4 $5 $zvsam $trace
rc=$?
if [ $rc -ne 0 ]; then errmsg "error in KSF1TEST"; fi

exit $rc
