#!/bin/bash

# ksf1rpo1: load KSDS KSF1NAME cluster, unload, and verify

########################################
# print error message and exit
########################################

function errmsg {
    echo ERROR: $1\; exiting
    exit 8
}

########################################
# setup
########################################

cd $(dirname $0)    # set to directory of script - z390/vsam1/demo/bash
cd ../../..         # up to z390

pgmname=ksf1rpo1
vsampath=vsam1/test
zvsam="zvsam(1)"
trace=""
if [ "$1" = "traceall" ]; then trace=traceall; shift; fi

########################################
# code
########################################

rc=0

# load KSDS KSF1NAME.[VES,VX0] from KSF1NAME.TF1

export INFILE=${vsampath}/KSF1NAME.TF1[RECFM=FT]
export OUTFILE=${vsampath}/TESTCAT.KSF1NAME
bash/exec linklib/REPRO $1 $2 $3 $4 $5 $zvsam $trace
rc=$?
if [ $rc -ne 0 ]; then errmsg "error in load of KSDS KSF1NAME"; fi

# unload KSDS KSF1NAME.VES to KSF1NAME.TF2

rm -f ${vsampath}/KSF1NAME.TF2
export INFILE=${vsampath}/TESTCAT.KSF1NAME
export OUTFILE=${vsampath}/KSF1NAME.TF2[RECFM=FT]
bash/exec linklib/REPRO $1 $2 $3 $4 $5 $zvsam $trace
rc=$?
if [ $rc -ne 0 ]; then errmsg "error in unload of KSDS KSF1NAME"; fi

# compare input and output QSAM files

diff ${vsampath}/KSF1NAME.TF1 ${vsampath}/KSF1NAME.TF2 > ${vsampath}/${pgmname}.DIF
rc=$?
if [ $rc -ne 0 ]; then errmsg "KSF1NAME.TF1 not equal to KSF1NAME.TF2"; fi

exit $rc
