#!/bin/bash

# rrf2rpo1: load/unload RRF2 records 1,3,5 using default RF RRN,RCD format

########################################
# print error message and exit
########################################

function errmsg {
    echo ERROR: $1\; exiting
    exit 8
}

########################################
# setup
########################################

cd $(dirname $0)     # set to directory of script - z390/vsam1/test/bash
cd ../../..          # up to z390

pgmname=rrf2rpo1
vsampath=vsam1/test
zvsam="zvsam(1)"
trace=""
if [ "$1" = "traceall" ]; then trace=traceall; shift; fi

########################################
# code
########################################

rc=0

# load RRF2.VES from RRF2.TF1

export INFILE=${vsampath}/RRF2.TF1
export OUTFILE=${vsampath}/TESTCAT.RRF2
bash/exec linklib/REPRO $1 $2 $3 $4 $5 $zvsam $trace
rc=$?
if [ $rc -ne 0 ]; then errmsg "error in REPRO load of RRF2"; fi

# save REPRO load stats

cp linklib/REPRO.LOG ${vsampath}/${pgmname}.RLG
if [ "$trace" = "traceall" ]; then cp linklib/REPRO.TRE ${vsampath}/${pgmname}.RLE; fi

# unload RRF2.VES to RRF2.TF2

rm -f ${vsampath}/RRF2.TF2
export INFILE=${vsampath}/TESTCAT.RRF2
export OUTFILE=${vsampath}/RRF2.TF2
bash/exec linklib/REPRO $1 $2 $3 $4 $5 $zvsam $trace
rc=$?
if [ $rc -ne 0 ]; then errmsg "error in REPRO unload of RRF2"; fi

# save REPRO unload stats

cp linklib/REPRO.LOG ${vsampath}/${pgmname}.RUG
if [ "$trace" = "traceall" ]; then cp linklib/REPRO.TRE ${vsampath}/${pgmname}.RUE; fi

# compare input and output QSAM files

diff ${vsampath}/RRF2.TF1 ${vsampath}/RRF2.TF2 > ${vsampath}/${pgmname}.DIF
rc=$?
if [ $rc -ne 0 ]; then errmsg "RRF2.TF1 not equal to RRF2.TF2"; fi

exit $rc
