#!/bin/bash

# rrv1rpq1: load/unload RRV1 VSAM using RECFM=V QSAM file
#
#           note: RRV1.TF1 QSAM input file is created by RRV1TEST.MLC

########################################
# print error message and exit
########################################

function errmsg {
    echo ERROR: $1\; exiting
    exit 8
}

########################################
# setup
########################################

cd $(dirname $0)     # set to directory of script - z390/vsam1/test/bash
cd ../../..          # up to z390

pgmname=rrv1rpq1
vsampath=vsam1/test
zvsam="zvsam(1)"
trace=""
if [ "$1" = "traceall" ]; then trace=traceall; shift; fi

########################################
# code
########################################

rc=0

# load RRV1.VES from ESV1.TQ1

export INFILE=${vsampath}/RRV1.TQ1[RECFM=V]
export OUTFILE=${vsampath}/TESTCAT.RRV1
bash/exec linklib/REPRO $1 $2 $3 $4 $5 $zvsam $trace
rc=$?
if [ $rc -ne 0 ]; then errmsg "error in REPRO load of RRV1"; fi

# save REPRO load stats

cp linklib/REPRO.LOG ${vsampath}/${pgmname}.RLG
if [ "$trace" = "traceall" ]; then cp linklib/REPRO.TRE ${vsampath}/${pgmname}.RLE; fi

# unload RRV1.VES to RRV1.TQ2

rm -f ${vsampath}/RRV1.TQ2
export INFILE=${vsampath}/TESTCAT.RRV1
export OUTFILE=${vsampath}/RRV1.TQ2[RECFM=V]
bash/exec linklib/REPRO $1 $2 $3 $4 $5 $zvsam $trace
rc=$?
if [ $rc -ne 0 ]; then errmsg "error in REPRO unload of RRV1"; fi

# save REPRO unload stats

cp linklib/REPRO.LOG ${vsampath}/${pgmname}.RUG
if [ "$trace" = "traceall" ]; then cp linklib/REPRO.TRE ${vsampath}/${pgmname}.RUE; fi

# compare input and output QSAM files

diff ${vsampath}/RRV1.TQ1 ${vsampath}/RRV1.TQ2 > ${vsampath}/${pgmname}.DIF
rc=$?
if [ $rc -ne 0 ]; then errmsg "RRV1.TQ1 not equal to RRV1.TQ2"; fi

exit $rc
