#!/bin/bash

# rrv1skp1: read RRDS variable length VSAM file SKP SEQ access using GENCB
#
#           note: first run rrv1test to create the RRDS

########################################
# print error message and exit
########################################

function errmsg {
    echo ERROR: $1\; exiting
    exit 8
}

########################################
# setup
########################################

cd $(dirname $0)     # set to directory of script - z390/vsam1/test/bash
cd ../../..          # up to z390

vsampath=vsam1/test
zvsam="zvsam(1)"
trace=""
if [ "$1" = "traceall" ]; then trace=traceall; shift; fi

########################################
# code
########################################

rc=0

# run RRV1SKP1 to read RRDS containing 3 variable length records

export VFILE=${vsampath}/TESTCAT.RRV1
bash/asmlg ${vsampath}/RRV1SKP1 $1 $2 $3 $4 $5 $zvsam $trace
rc=$?
if [ $rc -ne 0 ]; then errmsg "error in RRV1SKP1"; fi

exit $rc
