#!/bin/bash

# rrv1test: read RRDS variable length VSAM file

########################################
# print error message and exit
########################################

function errmsg {
    echo ERROR: $1\; exiting
    exit 8
}

########################################
# setup
########################################

cd $(dirname $0)     # set to directory of script - z390/vsam1/test/bash
cd ../../..          # up to z390

vsampath=vsam1/test
zvsam="zvsam(1)"
trace=""
if [ "$1" = "traceall" ]; then trace=traceall; shift; fi

########################################
# code
########################################

rc=0

# run RRV1TEST to create and test RRDS with 3 var records

export VFILE=${vsampath}/TESTCAT.RRV1
rm -f ${vsampath}/RRV1.VES
rm -f ${vsampath}/RRV1.VX0
bash/asmlg ${vsampath}/RRV1TEST $1 $2 $3 $4 $5 $zvsam $trace
rc=$?
if [ $rc -ne 0 ]; then errmsg "error in RRV1TEST"; fi

exit $rc
