call mac rt\test\TESTCAL1 maxcall(1)
me rt\test\TESTCAL1.BAL
call asm rt\test\TESTCAL1 maxesd(1)
me rt\test\TESTCAL1.PRN
call mac rt\test\TESTCAL1 maxfile(1)
me rt\test\TESTCAL1.BAL
call mac rt\test\TESTCAL1 maxlcl(1)
me rt\test\TESTCAL1.bal
call mac rt\test\TESTCAL1 maxgbl(1)
me rt\test\TESTCAL1.bal
call mac rt\test\TESTCAL1 maxline(1)
me rt\test\TESTCAL1.bal
call mac rt\test\TESTCAL1 maxparm(1)
me rt\test\TESTCAL1.bal
call mac rt\test\TESTRKD1 maxrld(1)
me rt\test\TESTRLD1.prn
call mac rt\test\TESTCAL1 maxsym(1)
me rt\test\TESTCAL1.bal
call asm rt\test\TESTINS1 maxsize(1)
me rt\test\TESTINS1.prn
rem end of rtmax.bat
