         MACRO
.*********************************************************************
.* Copyright 2008 Automated Software Tools Corporation               *
.* This source code is part of z390 zCOBOL/assembler/emulator package*
.* The z390 package is distributed under GNU general public license  *
.* Author - Don Higgins                                              *
.* Date   - 04/07/08                                                 *
.*********************************************************************
.* 04/09/08 initial coding for global ELSE
.* 10/05/08 ZSTRMAC
.*********************************************************************
         ELSE    
         COPY  ZC_WS
         AIF   (N'&SYSLIST GT 0)
               MNOTE 8,'ELSE - UNDEFINED VERB - &SYSLIST(1)'
         AEND
         AIF   (&IE_LVL LT 1)      
               MNOTE 8,'ELSE MISSING IF'
               MEXIT
         AEND
         AIF   (&IE_TYPE(&IE_LVL) NE 1)  
               MNOTE 8,'ELSE MISSING IF'
               MEXIT
         AEND
         AWHILE (&IE_ELSE(&IE_LVL))       
               AIF (&IE_LVL GT 1)
                   END_IF
               AELSE
                   MNOTE 8,'ELSE DUPLICATE FOR SAME IF'
                   MEXIT
               AEND
         AEND
         GEN_B IF_&IE_TCNT(&IE_LVL)._E
         :&IE_ELSE(&IE_LVL) SETB 1
         GEN_LABEL IF_&IE_TCNT(&IE_LVL)_&IE_BCNT(&IE_LVL),ELSE
         MEND
