         MACRO
.*********************************************************************
.* z390 - Mainframe assembler emulator and run-time engine
.* Copyright (C) 2021 z390 Assembler LLC
.*
.* This file is part of z390.
.*
.* z390 is free software; you can redistribute it and/or modify
.* it under the terms of the GNU General Public License as published by
.* the Free Software Foundation; either version 2 of the License, or
.* (at your option) any later version.
.* z390 is distributed in the hope that it will be useful,
.* but WITHOUT ANY WARRANTY; without even the implied warranty of
.* MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
.* GNU General Public License for more details.
.*
.* You should have received a copy of the GNU General Public License 
.* along with this program; if not, see https://www.gnu.org/licenses.
.*********************************************************************
.* Author - Don Higgins                                              *
.* Date   - 04/07/08                                                 *
.*********************************************************************
.* 11/26/08 initial coding GEN_PM_LVL                      
.* 10/06/08 ZSTRMAC
.*********************************************************************
         GEN_PM_LVL &LAB 
         COPY  ZC_WS
         :&IE_LVL SETA &IE_LVL+1
         :&IE_TCNT(&IE_LVL) SETA &PM_LAB
         :&IE_TYPE(&IE_LVL) SETA 4 PM TYPE
         :&IE_PM_LAB(&IE_LVL) SETC '&LAB'
         MEND
