#!/bin/bash

# bldcbllib: rebuild zcobol/lib/ZC390LIB.390

set -e              # exit on all errors
cd $(dirname $0)    # set to directory of script
cd ..               # go to root

sysmac='sysmac(mac)'
syscpy='syscpy(mac+zcobol/lib)'
sys390='sys390(zcobol/lib)'

bash/asm zcobol/lib/ABORT $sysmac $syscpy $1 $2 $3 $4 $5 $6 $7 $8 $9
bash/asm zcobol/lib/ACCEPT $sysmac $syscpy $1 $2 $3 $4 $5 $6 $7 $8 $9
bash/asm zcobol/lib/CVTTOHEX $sysmac $syscpy $1 $2 $3 $4 $5 $6 $7 $8 $9
bash/asm zcobol/lib/DISPLAY $sysmac $syscpy $1 $2 $3 $4 $5 $6 $7 $8 $9
bash/asm zcobol/lib/INSPECT $sysmac $syscpy $1 $2 $3 $4 $5 $6 $7 $8 $9
bash/asm zcobol/lib/ZC390NUC $sysmac $syscpy $1 $2 $3 $4 $5 $6 $7 $8 $9
bash/asml zcobol/lib/ZC390LIB $sysmac $syscpy $sys390 RMODE24 $1 $2 $3 $4 $5 $6 $7 $8 $9

echo "Verify ZC390LIB.390 build ok"
