#!/bin/bash

# blddist: Script to create z390 distribution zip file
# passing parm "clean" will remove repo ignored files and rebuild prior to dist build

set -e                          # exit on all errors
cd $(dirname $0)                # set to directory of script
cd ..                           # cd back to root       

root_dir=$(pwd)
version_tag=$(git describe)

if [ "$1" == "clean" ];         # if "clean" parm passed
then
    git clean -dfX              # delete all git ignored files
fi

mkdir -p build                  # create build folder if does not exist
rm -rf build/z390_${version_tag}    # delete version build directory

bash/bldjar                     # create the z390 jar

cd build
mkdir z390_${version_tag}
cd z390_${version_tag}

# add core files to the build dir
cp ${root_dir}/z390.jar .       # jar
core_dirs=( bash bat mac zcobol cics vse linklib )
for dir in ${core_dirs[@]}; do
    cp -R ${root_dir}/${dir} .        # unix bash scripts
done

# add test and supplimental components
supp_dirs=( assist demo guam qsam rt soa sort structuredmacros tests vsam1 vsam2 zopcheck zpar )
for dir in ${supp_dirs[@]}; do
    cp -R ${root_dir}/${dir} .        # unix bash scripts
done

# create zip package
cd ..
zip -r z390_${version_tag}.zip z390_${version_tag}
