#!/bin/bash

# blddist: Script to create z390 distribution zip file
# passing parm "clean" will remove repo ignored files and rebuild prior to dist build

set -e                                  # exit on all errors
cd $(dirname $0)                        # set to directory of script
cd ..                                   # cd back to root       

root_dir=$(pwd)
version_tag=$(git describe)
dist_folder=dist

if [ "$1" == "clean" ];                 # if "clean" parm passed
then
    git clean -dfX                            # delete all git ignored files
fi

# build jar
bash/bldjar                                   # create the z390 jar

# Create/clean dist folder
mkdir -p ${dist_folder}                       # create dist folder if does not exist
echo "/**" > ${dist_folder}/.gitignore        # ignore the dist folder
rm -rf ${dist_folder}/z390_${version_tag}     # delete version dist directory
rm -f ${dist_folder}/z390_${version_tag}.zip  # delete the zip

# build javadocs
bash/bldjavadoc 'build/javadoc'               # docs in build/javadocs

# generate HLASM compatible SPM's
bash/bldzstrmac 'build/zstrmac'

cd ${dist_folder}
mkdir z390_${version_tag}
cd z390_${version_tag}

# add core files to the build dir
cp ${root_dir}/z390.jar .               # jar
core_dirs=( bash bat mac zcobol cics linklib README.txt LICENSE )
for dir in ${core_dirs[@]}; do
    cp -R ${root_dir}/${dir} .          # unix bash scripts
done

# add test and supplimental components
supp_dirs=( assist demo guam qsam bsam rt soa sort structuredmacros tests vsam1 
vsam2 vse zopcheck zpar )
for dir in ${supp_dirs[@]}; do
    cp -R ${root_dir}/${dir} .          # unix bash scripts
done

# add structured programming macros to mac/spm folder
mkdir -p mac/spm
cp -R ${root_dir}/build/zstrmac/* mac/spm

# add javadoc
mkdir -p javadoc
cp -R ${root_dir}/build/javadoc/* javadoc

# remove components not required for distribution
del_items=('bash/bldjar' 'bat/BLDJAR.BAT' 'bash/blddist' 'bash/relver' 'bat/RELVER.BAT')
for item in ${del_items[@]}; do
    rm ${item}        # unix bash scripts
done

# create zip package
cd ..
zip -q -dd -r z390_${version_tag}.zip z390_${version_tag}
