#!/bin/bash

# bldguam: rebuild guam demo and test programs

set -e              # exit on all errors
cd $(dirname $0)    # set to directory of script
cd ..               # go to root

bash/asml guam/demo/DEMOAPL1 guam
bash/asml guam/demo/DEMOGUI1 guam
bash/asml guam/demo/DEMOGUI2 guam
bash/asml guam/demo/DEMOGUI3 guam
bash/asml guam/demo/DEMOGUI4 guam
bash/asml guam/demo/DEMOGUI5 guam
bash/asml guam/demo/DEMOGUI6 guam
bash/asml guam/demo/HELLO1   guam
bash/asml guam/demo/HELLO2   guam
bash/asml guam/demo/HELLO3   guam
bash/asml guam/test/AID      guam
bash/asml guam/test/EXSAMPL2 guam
bash/asml guam/test/TESTGP1  guam
bash/asml guam/test/TESTGP2  guam
bash/asml guam/test/TESTGP3  guam
bash/asml guam/test/TESTGP4  guam
bash/asml guam/test/TGUAM    guam
