#!/bin/bash

# bldjavadoc: rebuild z390 javadoc files from sources

#set -e             # exit on all errors
cd $(dirname $0)    # set to directory of script
cd ..               # up one to z390 directory

DEST=$1
if [ -z "${DEST}" ]; then 
    DEST="build/javadoc"
fi
mkdir -p "${DEST}"   # create folder if does not exist

javadocdir=build/javadoc  # directory for javadoc files

mkdir -p "${DEST}"   # create directory if it does not exist

# empty destination directory
rm -rf ${DEST}/*

# build the javadoc
echo "Building javadoc from src/*.java into ${DEST} directory ..."
javadoc -quiet -Xdoclint:none -d ${DEST} src/*.java
ec=$?
echo "The exit code of the javadoc command is $ec"
if [ $ec -ne 0 ]; then echo "bldjavadoc Error encountered building javadoc"; fi
exit $ec
