#!/bin/bash

# bldjavadoc: rebuild z390 javadoc files from sources

#set -e             # exit on all errors
cd $(dirname $0)    # set to directory of script
cd ..               # up one to z390 directory

javadocdir=docenv/javadoc  # directory for javadoc files

mkdir -p "${javadocdir}"   # create directory if it does not exist

# empty destination directory
rm -rf ${javadocdir}/*

# build the javadoc
echo "Building javadoc from src/*.java into ${javadocdir} directory ..."
javadoc -d ${javadocdir} src/*.java
ec=$?
echo "The exit code of the javadoc command is $ec"
if [ $ec -ne 0 ]; then echo "bldjavadoc Error encountered building javadoc"; fi
exit $ec
