#!/bin/bash

# bldlib: rebuild linkib library

set -e              # exit on all errors
cd $(dirname $0)    # set to directory of script
cd ..               # go to root

bash/asml linklib/REPRO @linklib/LINKLIB.OPT
bash/asml linklib/SUPERZAP @linklib/LINKLIB.OPT
bash/asml linklib/UNREF @linklib/UNREF.OPT
bash/asm linklib/FPCONVRT @linklib/LINKLIB.OPT
bash/asm linklib/FPCONMFC @linklib/LINKLIB.OPT
bash/asm linklib/CVTTOHEX @linklib/LINKLIB.OPT
bash/asm linklib/SQXTR @linklib/LINKLIB.OPT
bash/asm linklib/DAT @linklib/LINKLIB.OPT

bash/asmlg linklib/IEFBR14 @linklib/LINKLIB.OPT
bash/asmlg linklib/TESTFPC1 @linklib/LINKLIB.OPT
bash/asmlg linklib/TESTFPC2 @linklib/LINKLIB.OPT

bash/asm  linklib/RTGENDIR @linklib/RTGENDIR.OPT
bash/asm  linklib/RTGENCMP @linklib/RTGENCMP.OPT
