#!/bin/bash

# cblc: translate CBL to MLC using zc390 and assemble using mz390 

# debug flag; 0=no debug, 1=debug
debug=0

ECHO=0
if [ "$1" = "tron" ] || [ "$1" = "TRON" ]; then
#    echo "setting echo to 1"
	ECHO=1
	shift
fi

if [ -f "$1.CBL" ]; then
    if [ -f "$1.MLC" ]; then rm $1.MLC; fi
    if [ -f "$1.BAL" ]; then rm $1.BAL; fi
    if [ -f "$1.ERR" ]; then rm $1.ERR; fi
    if [ -f "$1.LST" ]; then rm $1.LST; fi
    if [ -f "$1.PRN" ]; then rm $1.PRN; fi
    if [ -f "$1.OBJ" ]; then rm $1.OBJ; fi
    if [ -f "$1.STA" ]; then rm $1.STA; fi
    if [ -f "$1.390" ]; then rm $1.390; fi
    if [ -f "$1.cpp" ]; then rm $1.cpp; fi
    if [ -f "$1.java" ]; then rm $1.java; fi
    if [ -f "$1.class" ]; then rm $1.class; fi

    # extract longest substring that ends with "/"
    dir=${0%/*}
    if [ $debug -eq 1 ]; then echo "cblc: dir=$dir"; fi

    # get the z390 directory
    zdir=$(dirname $0)
    zdir=$(cd $zdir && pwd)
    zdir=$(dirname $zdir)
    if [ $debug -eq 1 ]; then echo "cblc: zdir=$zdir"; fi

    ${dir}/zc390 $1 $2 $3 $4 $5 $6 $7 $8 $9
    rc=$?
    if [ $debug -eq 1 ]; then echo "cblc: zc390 rc=$rc"; fi
    if [ "$rc" -eq "0" ]; then
        cblopt='@'$zdir'/zcobol/opt/CBLOPT'
        sysmac='sysmac('$zdir'/zcobol/mac+'$zdir'/mac)'
        syscpy='syscpy(+'$zdir'/zcobol/cpy)'
        if [ $debug -eq 1 ]; then echo "cblc: cblopt=$cblopt"; fi
        ${dir}/mz390 $1 $cblopt $sysmac $syscpy $2 $3 $4 $5 $6 $7 $8 $9
        rc=$?
        if [ $debug -eq 1 ]; then echo "cblc: mz390 rc=$rc"; fi
        if [ "$rc" -ne "0" ]; then
            echo "cblc: mz390 error; mz390 rc=$rc; see errors on mz390 generated $1.BAL file and console"
        fi
    else
        echo "cblc: zc390 error; zc390 rc=$rc; see console"
    fi
else
    echo "cblc: error; no zcobol program found: $1.CBL"
fi
