#!/usr/bin/python

# Scan files in a folder to report on usage of z390 structured macro syntax
# This means the use of the following macro instructions
# * AELSE
# * AELSEIF
# * AWHILE
# * AEND
# 
# 
