#!/bin/bash

# exec: execute z390 load module

# debug flag; 0=no debug, 1=debug
debug=0

rc=0
trace=0

if [ $# -gt 0 ]; then
    # save current nocasematch setting
    SHELLNOCASEMATCH=$(shopt -p nocasematch)
    shopt -s nocasematch
    case $1 in
        "tron")
            shift
            trace=1
            ;;
        "troff")
            shift
            trace=0
            ;;
    esac
    # restore nocasematch setting
    $SHELLNOCASEMATCH
fi

if [ $trace -eq 1 ]; then set -x; fi

if [ $# -eq 0 ] || [ -z "$1" ]; then echo "exec ERROR: missing file name"; exit 16; fi

# remove trailing ".390", if any
zFile="${1%.390}"

# error if missing name to left of ".390"
if [ -z "$zFile" ]; then echo "exec ERROR: invalid file name $1"; exit 16; fi
# error if input file with 390 extension does not exist
if [ ! -f "$zFile".390 ]; then echo "exec ERROR: file $zFile.390 not found"; exit 16; fi

# remove previously created files, if any
if [ -f "$zFile.LOG" ]; then rm $zFile.LOG; fi
if [ -f "$zFile.ERR" ]; then rm $zFile.ERR; fi
if [ -f "$zFile.STA" ]; then rm $zFile.STA; fi
#if [ -f $zFile.TR* ]; then rm $zFile.TR*; fi
# .TR* file(s) exist if "ls" exit status is 0
if ls $zFile.TR* 1>/dev/null 2>&1; then rm -f $zFile.TR*; fi

# extract longest substring that ends with "/"
dir=${0%/*}

${dir}/ez390 $zFile $2 $3 $4 $5 $6 $7 $8 $9
rc=$?
if [ $debug -eq 1 ]; then echo "exec: ez390 rc=$rc"; fi
# rc is a user return code or an exit code from ez390.java; may not be an error!
if [ $rc -ne 0 ]; then
    echo "exec ERROR: ez390 rc=$rc; see errors in $zFile.LOG file and on console"
fi

exit $rc
