#!/bin/bash

# ivp: run installation verification procedure (iz390) with java runtime options

# debug flag; 0=no debug, 1=debug
debug=0

# get full directory path to z390.jar; assumes that this bash script is in the z390 subdirectory
jardir=$(dirname $0)
jardir=$(cd $jardir && pwd)
jardir=$(dirname $jardir)

if [ $debug -eq 1 ]; then echo "ivp jardir=$jardir $@"; fi
java -classpath ${jardir}/z390.jar -Xrs -Xms150000K -Xmx150000K $J2SEOPTIONS iz390 $1 $2 $3 $4 $5 $6 $7 $8 $9

rc=$?
# rc = 1 for Java issues; all other non-zero values for assembly issues
if [ $debug -eq 1 ]; then echo "ivp after java command; rc=$rc"; fi

if [ $rc -eq 0 ]; then
    :
elif [ $rc -eq 4 ]; then
    echo "ivp WARNING: See warnings on iz390 generated output"
else
    echo "ivp ERROR: See errors on iz390 generated output"
fi

exit $rc