#!/bin/bash

# runasmtests: regression test z390 instructions

set -e              # exit on all errors
cd $(dirname $0)    # set to directory of script
cd ..

sysmac='sysmac(mac)'
optable='optable(z390)'

bash/asm   tests/TESTINS1 trace noloadhigh $sysmac
bash/asmlg tests/TESTINS2 trace noloadhigh $sysmac
bash/asmlg tests/TESTINS3 trace noloadhigh $sysmac
bash/asmlg tests/TESTINS4 trace noloadhigh $sysmac
bash/asmlg tests/TESTINS5 trace noloadhigh $sysmac $optable
bash/asmlg tests/TESTDFP1 trace noloadhigh $sysmac $optable
bash/asmlg tests/TESTDFP2 trace noloadhigh $sysmac $optable
bash/asmlg tests/TESTLITS trace noloadhigh $sysmac
bash/zopcheck
echo "Verify tests ran without errors"
