#!/bin/bash

# runasmdemos: run HELLO, DEMOM8Q1, TESTDCB1

set -e              # exit on all errors
cd $(dirname $0)    # set to directory of script
cd ..

bash/asmlg demo/HELLO $1 $2 $3 $4 $5 $6 $7 $8 $9
echo "Verify Hello World WTO"

bash/asm demo/DEMOM8Q1.ZSM $1 $2 $3 $4 $5 $6 $7 $8 $9
echo "Verify rc=0; see PRN file for 8 queens solutions"

export SYSUT1=demo/TESTDCB1.TF1
export SYSUT2=demo/TESTDCB1.TF2
export SYSOUT=demo/TESTDCB1.TF3

bash/asmlg demo/TESTDCB1 $1 $2 $3 $4 $5 $6 $7 $8 $9
cat demo/TESTDCB1.TF2
echo "Verify demo/TESTDCB1 copied demo/TESTDCB1.TF1 to demo/TESTDCB1.TF2"
echo "Verify demo/TESTDCB1 wrote to demo/TESTDCB1.TF3"
