#!/bin/bash

# runasmtests: regression test z390 instructions

set -e              # exit on all errors
cd $(dirname $0)    # set to directory of script
cd ..

sysmac='sysmac(mac)'
optable='optable(z390)'

bash/asm tests/TESTINS1 trace $sysmac
bash/asmlg tests/TESTINS2 trace $sysmac
bash/asmlg tests/TESTINS3 trace $sysmac
bash/asmlg tests/TESTINS4 trace $sysmac
bash/asmlg tests/TESTINS5 trace $sysmac $optable
bash/asmlg tests/TESTDFP1 trace $sysmac $optable
bash/asmlg tests/TESTDFP2 trace $sysmac $optable
bash/zopcheck
echo "Verify tests ran without errors"
