#!/bin/bash

# runassist: run demo and test ASSIST programs

# debug flag; 0=no debug, 1=debug
debug=0

set -e              # exit on all errors
cd $(dirname $0)    # set to directory of script
cd ..

export XPRNT=assist/demo/DEMOAST1.XPR
bash/asmlg assist/demo/DEMOAST1 ASSIST TRACEALL
rc=$?
if [ $debug -eq 1 ]; then echo "DEMOAST1: rc=$rc"; fi
if [ "$rc" -ne "0" ]; then
    echo "Error in DEMOAST1 rc=$rc - exiting"
    exit $rc
fi

export XREAD=assist/test/TESTAST1.XRD
export XPRNT=assist/test/TESTAST1.XPR
export XPNCH=assist/test/TESTAST1.XPH
export XGET=assist/test/TESTAST1.XGT
export XPUT=assist/test/TESTAST1.XPT
bash/asmlg assist/test/TESTAST1 ASSIST TRACEALL
rc=$?
if [ $debug -eq 1 ]; then echo "TESTAST1: rc=$rc"; fi
if [ "$rc" -ne "0" ]; then
    echo "Error in TESTAST1 rc=$rc - exiting"
    exit $rc
fi

export XPRNT=assist/test/TSTXDECI.XPR
bash/asmlg assist/test/TSTXDECI ASSIST 'PARM(v)'
rc=$?
if [ $debug -eq 1 ]; then echo "TSTXDECI: rc=$rc"; fi
if [ "$rc" -ne "0" ]; then
    echo "Error in TSTXDECI rc=$rc - exiting"
    exit $rc
fi

export XPRNT=assist/test/TSTXHEXI.XPR
bash/asmlg assist/test/TSTXHEXI ASSIST 'PARM(v)'
rc=$?
if [ $debug -eq 1 ]; then echo "TSTXHEXI: rc=$rc"; fi
if [ "$rc" -ne "0" ]; then
    echo "Error in TSTXHEXI rc=$rc - exiting"
    exit $rc
fi

export XPRNT=assist/test/SOLP06.XPR
bash/asmlg assist/test/SOLP06 ASSIST 'PARM(v)'
rc=$?
if [ "$rc" -ne "0" ]; then
    echo "Error in SOLP06 rc=$rc - exiting"
    exit $rc
fi
diff -q assist\test\SOLP06.XPR assist\test\SOLP06.TF1 &>/dev/null
rc1=$?
if [ $rc1 -eq 0 ]; then x=""; else x=" not"; fi
echo "SOLP06: Test run was$x successful"

echo "Verify ASSIST demo and test"
