#!/bin/bash
#######################################################################
# z390 - Mainframe assembler emulator and run-time engine
# Copyright (C) 2021 z390 Assembler LLC
#
# This file is part of z390.
# z390 is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# z390 is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, see <https://www.gnu.org/licenses/>.
#######################################################################

# runcmdproc: run programs that test CMDPROC (SVC 34)

# debug flag; 0=no debug, 1=debug
debug=0

#set -e              # exit on all errors
cd $(dirname $0)    # set to directory of script
cd ..

########################################
# path
########################################

rtpath=rt/test

# Test one Command Processor

program=TESTCMD3

# build test program
bash/asml ${rtpath}/${program}
rc=$?
if [ $debug -eq 1 ]; then echo "build ${program}: rc=$rc"; fi
if [ "$rc" -ne "0" ]; then
    echo "Error building ${program} rc=$rc - exiting"
    exit $rc
fi

# name of test file
export TESTCMDFILE=${rtpath}/bash/testcmd3

bash/exec ${rtpath}/${program}
rc=$?
if [ $debug -eq 1 ]; then echo "${program}: rc=$rc"; fi
if [ "$rc" -ne "0" ]; then
    echo "Error ${program} rc=$rc - exiting"
    exit $rc
fi

# Test two command processors (3 tests)
# 1. Both have same number of lines of output
# 2. Second CP has more lines of output
# 3. First CP has more lines of output

program=TESTCMD4

# build test program
bash/asml ${rtpath}/${program}
rc=$?
if [ $debug -eq 1 ]; then echo "build ${program}: rc=$rc"; fi
if [ "$rc" -ne "0" ]; then
    echo "Error building ${program} rc=$rc - exiting"
    exit $rc
fi

# names of test files for first test
export TESTCMDFILE1=${rtpath}/bash/testcmd4a
export TESTCMDFILE2=${rtpath}/bash/testcmd4b

bash/exec ${rtpath}/${program}
rc=$?
if [ $debug -eq 1 ]; then echo "${program} test 1: rc=$rc"; fi
if [ "$rc" -ne "0" ]; then
    echo "Error ${program} rc=$rc - exiting"
    exit $rc
fi

# names of test files for second test
export TESTCMDFILE1=${rtpath}/bash/testcmd4a
export TESTCMDFILE2=${rtpath}/bash/testcmd4c

bash/exec ${rtpath}/${program}
rc=$?
if [ $debug -eq 1 ]; then echo "${program} test 2: rc=$rc"; fi
if [ "$rc" -ne "0" ]; then
    echo "Error ${program} rc=$rc - exiting"
    exit $rc
fi

# names of test files for third test
export TESTCMDFILE1=${rtpath}/bash/testcmd4c
export TESTCMDFILE2=${rtpath}/bash/testcmd4b

bash/exec ${rtpath}/${program}
rc=$?
if [ $debug -eq 1 ]; then echo "${program} test 3: rc=$rc"; fi
if [ "$rc" -ne "0" ]; then
    echo "Error ${program} rc=$rc - exiting"
    exit $rc
fi

echo "Verify CMDPROC tests"
