#!/bin/bash

# runvsedemos: run vse demos under z390

# debug flag; 0=no debug, 1=debug
debug=0

set -e              # exit on all errors
cd $(dirname $0)    # set to directory of script
cd ..

sysmac='sysmac(vse/mac+mac)'

bash/asmlg vse/demo/DEMOVSE1 $sysmac
rc=$?
if [ $debug -eq 1 ]; then echo "DEMOVSE1: rc=$rc"; fi
if [ "$rc" -ne "0" ]; then echo "Error in DEMOVSE1"; fi

bash/asmlg vse/demo/DEMOVSE2 $sysmac
rc=$?
if [ $debug -eq 1 ]; then echo "DEMOVSE2: rc=$rc"; fi
if [ "$rc" -ne "0" ]; then echo "Error in DEMOVSE2"; fi

export SYSUT1=vse/demo/DEMOVSE3.TF1
export SYSUT2=vse/demo/DEMOVSE3.TF2

bash/asmlg vse/demo/DEMOVSE3 $sysmac
rc=$?
if [ $debug -eq 1 ]; then echo "DEMOVSE3: rc=$rc"; fi
if [ "$rc" -ne "0" ]; then echo "Error in DEMOVSE3"; fi

echo "Verify vse demos DEMOVSE1, DEMOVSE2, and DEMOVSE3 ended okay"
echo "Verify vse/demo/ files DEMOVSE3.TF1 and DEMOVSE3.TF2 are identical"
