#!/bin/bash

# runzpar: run ZPAR asm and cbl demos
#
set -e              # exit on all errors
cd $(dirname $0)    # set to directory of script
cd ..

bash/asmlg demo/HELLO trace

sysparm="SYSPARM(demo/HELLO)"
bash/mac zpar/ZPARTRS $sysparm

bash/cblclg zcobol/demo/HELLO trace

sysparm="SYSPARM(zcobol/demo/HELLO)"
bash/mac zpar/ZPARTRS $sysparm

# done with tests
echo "See generated TRS files to verify ZPAR demos ok"
