#!/bin/bash

# zopcheck: regression test z390 instructions

set -e              # exit on all errors
cd $(dirname $0)    # set to directory of script
cd ..

export SNAPOUT=zopcheck/SNAPOUT.TXT

sysmac='sysmac(mac)'
syscpy='syscpy(zopcheck+mac)'
optable='optable(z390)'

bash/asmlg zopcheck/ZOPCHECK trace $sysmac $syscpy $optable

# done with tests
echo "Verify zopcheck ran without errors"
