#!/bin/bash
#######################################################################
# z390 - Mainframe assembler emulator and run-time engine
# Copyright (C) 2021 z390 Assembler LLC
#
# This file is part of z390.
# z390 is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# z390 is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, see <https://www.gnu.org/licenses/>.
#######################################################################
set -e              # exit on all errors

pushd $(dirname $0) > /dev/null
cd ..    # get z390 base
Z390BASE=$(pwd)
popd > /dev/null

SRC=$1
DEST=$2
if [ -z "${DEST}" ]; then
    echo "Usage: zstrmac <source> <dest>"
    exit 1
fi

ZSTR="${Z390BASE}/rt/test/ZSTRMAC2.ZSM"
SYSUT1=${SRC} SYSUT2=${DEST} ${Z390BASE}/bash/mz390 ${ZSTR} NOASM STATS
