#!/bin/bash

# z390cicg: start CICS transaction server on this processor

###############################
# print error message and exit
###############################

function wrong {
    echo ERROR ERROR ERROR
    exit 8
}

####################
# path
####################

cicspath=cics
export CICSPATH=cics

program=Z390CICS
export Z390INI=${cicspath}/${program}.INI

#${cicspath}/bash/z390file
# z390file uses the $CICSPATH environment variable and
# echos export statements for all zCICS file definitions.
# Evaluate the export statements so environment
# variables are accessible here.

eval $(${cicspath}/bash/z390file)

bash/ez390 ${cicspath}/${program} NOTIME $1 $2 $3 $4 $5 CON
rc=$?
if [ $rc -ne 0 ]; then wrong; fi

echo Verify startup of CICS

exit 0
