name: Build z390 (Windows)
on:
  push:
    branches:
      - 'main'
      - 'feature/**'
      - '!**-nobuild'

jobs:
  build:
    runs-on: windows-2019
    steps:
      - name: Checkout main
        uses: actions/checkout@v2
      - name: Build z390 (win)
        shell: cmd
        run: call .\BUILD.BAT