name: Publish docs via GitHub Pages
on: 
  push:
    branches:
      - main
      - doc/**

env:
  JAVA_DISTRIBUTION: temurin
  JAVA_VERSION: 21

jobs:
  deploy:
    name: Deploy docs
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          lfs: true
      - name: version
        run: echo "version=$(git describe --tags)" >> $GITHUB_OUTPUT
        id: version
      - uses: actions/setup-python@v4
        with:
          python-version: 3.11
      - uses: actions/setup-java@v3
        with:
          distribution: ${{ env.JAVA_DISTRIBUTION }}
          java-version: ${{ env.JAVA_VERSION }}
      - run: pip install -r doc/requirements.txt
      - run: bash/bldjavadoc doc/javadoc
      - run: mkdocs gh-deploy --force
        env:
          Z390_VERSION: ${{ steps.version.outputs.version }}